#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Dhan Sector-Based Trading Program with Stop Loss
------------------------------------------------
This program trades stocks based on sector performance data from sector.csv:
1. Reads sector.csv generated by the sector performance scraper
2. Makes trading decisions based on sector performance (buy positive, sell negative)
3. Executes trades through Dhan trading API using provided credentials
4. Monitors and exits positions based on:
   - Sector performance changes
   - Stop loss price levels
   - Target price levels
"""

# Standard library imports
import os
import time
import json
import logging
import traceback
from datetime import datetime

# Third-party imports
import pandas as pd

# Dhan API imports
from dhanhq import dhanhq

# =================================================================
# Logging Setup
# =================================================================

# Create logs directory if it doesn't exist
os.makedirs('logs', exist_ok=True)

# Setup logging with both file and console output
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(f"logs/dhan_sector_trader_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger()

# =================================================================
# Constants
# =================================================================

# Configuration files
SECTOR_MAPPING_FILE = "sector_mapping.json"
TRADING_CONFIG_FILE = "trading_config.json"
SECURITY_IDS_FILE = "security_ids.xlsx"

# Input/Output files
SECTOR_PERFORMANCE_FILE = "sector.csv"
POSITIONS_FILE = "dhan_positions.json"

# Default interval between checks (in seconds)
DEFAULT_CHECK_INTERVAL = 60

# =================================================================
# Utility Functions
# =================================================================

def log_separator(message=""):
    """Print a separator line in the log for better readability"""
    separator = "=" * 50
    if message:
        logger.info(f"\n{separator}\n{message}\n{separator}")
    else:
        logger.info(f"\n{separator}")

# =================================================================
# Configuration and Setup Functions
# =================================================================

def load_config():
    """Load trading configuration from JSON file"""
    try:
        logger.info(f"Loading trading configuration from {TRADING_CONFIG_FILE}")
        if os.path.exists(TRADING_CONFIG_FILE):
            with open(TRADING_CONFIG_FILE, 'r') as f:
                config = json.load(f)
                
                # Validate required fields
                required_fields = ['client_id', 'access_token', 'place_new_orders']
                missing_fields = [field for field in required_fields if field not in config]
                
                if missing_fields:
                    logger.error(f"Trading config missing required fields: {missing_fields}")
                    return None
                
                logger.info(f"Configuration loaded successfully")
                
                # Check for active tickers
                tickers = config.get('tickers', [])
                active_tickers = [t for t in tickers if t.get('active', False)]
                logger.info(f"Found {len(active_tickers)} active tickers out of {len(tickers)} total")
                
                return config
        else:
            logger.error(f"Config file {TRADING_CONFIG_FILE} not found")
            return None
    except Exception as e:
        logger.error(f"Error loading configuration: {str(e)}")
        logger.error(traceback.format_exc())
        return None

def load_sector_mapping():
    """Load sector mapping from JSON file"""
    try:
        logger.info(f"Loading sector mapping from {SECTOR_MAPPING_FILE}")
        with open(SECTOR_MAPPING_FILE, 'r') as f:
            mapping = json.load(f)
            logger.info(f"Sector mapping loaded successfully with {len(mapping)} tickers")
            
            # Get unique sectors for reference
            unique_sectors = set(mapping.values())
            logger.info(f"Found {len(unique_sectors)} unique sectors")
            
            return mapping
    except Exception as e:
        logger.error(f"Error loading sector mapping: {str(e)}")
        logger.error(traceback.format_exc())
        # Return empty dict if file not found or other error
        return {}

def load_security_ids():
    """Load security IDs mapping from Excel file with correct column mapping"""
    try:
        logger.info(f"Loading security IDs from {SECURITY_IDS_FILE}")
        
        if not os.path.exists(SECURITY_IDS_FILE):
            logger.error(f"Security IDs file {SECURITY_IDS_FILE} not found")
            return {}
        
        # Read Excel file using pandas
        df = pd.read_excel(SECURITY_IDS_FILE)
        logger.info(f"Successfully read Excel file with {len(df)} rows")
        
        # Log the column names to verify format
        logger.info(f"Excel columns: {df.columns.tolist()}")
        
        # Use the specific column names from the Excel file
        symbol_col = 'SEM_TRADING_SYMBOL'
        id_col = 'SEM_SMST_SECURITY_ID'
        
        if symbol_col not in df.columns:
            logger.error(f"Symbol column '{symbol_col}' not found in Excel file.")
            return {}
            
        if id_col not in df.columns:
            logger.error(f"Security ID column '{id_col}' not found in Excel file.")
            return {}
            
        logger.info(f"Using columns: Symbol='{symbol_col}', ID='{id_col}'")
        
        # Log the first few rows for debugging
        logger.info("First few rows for debugging:")
        sample_rows = min(5, len(df))
        for i in range(sample_rows):
            logger.info(f"Row {i+1}: Symbol={df.iloc[i][symbol_col]}, ID={df.iloc[i][id_col]}")
            
        # Create dictionary from DataFrame
        security_ids = {}
        for _, row in df.iterrows():
            # Skip rows with NaN values
            if pd.isna(row[symbol_col]) or pd.isna(row[id_col]):
                continue
                
            symbol = str(row[symbol_col]).strip()
            # Convert to int first to remove decimals, then to string
            try:
                security_id = str(int(row[id_col])).strip()
            except:
                # If conversion fails, use as is
                security_id = str(row[id_col]).strip()
            
            # Skip rows with empty symbols or IDs
            if not symbol or symbol == 'nan' or not security_id or security_id == 'nan':
                continue
                
            # Add to mapping - include both formats (with and without .NS)
            security_ids[symbol] = security_id  # Base symbol
            security_ids[f"{symbol}.NS"] = security_id  # With .NS suffix
            
        logger.info(f"Security IDs mapping created with {len(security_ids)} entries")
        
        # Check for key stocks
        test_symbols = ["SYNGENE", "SYNGENE.NS", "GRANULES", "GRANULES.NS", "ZEEL", "ZEEL.NS", "SBILIFE", "SBILIFE.NS", "RBLBANK", "RBLBANK.NS"]
        logger.info("Checking for critical symbols:")
        for sym in test_symbols:
            if sym in security_ids:
                logger.info(f"Found ID for {sym}: {security_ids[sym]}")
            else:
                logger.warning(f"No ID found for {sym}")
        
        # Log a sample of the security IDs for reference
        sample_ids = list(security_ids.items())[:10]
        logger.info(f"Sample security IDs: {sample_ids}")
                
        return security_ids
        
    except Exception as e:
        logger.error(f"Error loading security IDs from Excel: {str(e)}")
        logger.error(traceback.format_exc())
        return {}

def validate_security_ids(security_ids, config):
    """Validate that all configured tickers have security IDs"""
    log_separator("VALIDATING SECURITY IDS")
    
    if not config or 'tickers' not in config:
        logger.warning("No tickers found in configuration")
        return
        
    tickers = [t['symbol'] for t in config['tickers'] if t.get('active', False)]
    logger.info(f"Found {len(tickers)} active tickers to validate")
    
    missing_ids = []
    found_ids = []
    
    for symbol in tickers:
        # Try different variations
        found = False
        variations = [
            symbol,
            symbol.replace('.NS', ''),
            symbol.replace('.NS', '') + '.NS'
        ]
        
        for var in variations:
            if var in security_ids:
                logger.info(f"Found security ID for {symbol} via {var}: {security_ids[var]}")
                found = True
                found_ids.append((symbol, var, security_ids[var]))
                break
                
        if not found:
            missing_ids.append(symbol)
            logger.error(f"No security ID found for {symbol}")
    
    if missing_ids:
        logger.error(f"Missing security IDs for {len(missing_ids)} tickers: {missing_ids}")
    else:
        logger.info("All active tickers have security IDs")
        
    # Return the validation results
    return {
        "missing": missing_ids,
        "found": found_ids
    }

def load_positions():
    """Load current trading positions from JSON file"""
    try:
        if os.path.exists(POSITIONS_FILE):
            with open(POSITIONS_FILE, 'r') as f:
                positions = json.load(f)
                logger.info(f"Loaded {len(positions)} existing positions")
                
                # Count positions by status
                open_positions = [p for p in positions if p.get('status') == 'OPEN']
                closed_positions = [p for p in positions if p.get('status') == 'CLOSED']
                logger.info(f"Positions: {len(open_positions)} open, {len(closed_positions)} closed")
                
                # Log open positions for reference
                if open_positions:
                    logger.info("Open positions:")
                    for p in open_positions:
                        logger.info(f"  {p.get('transaction_type')} {p.get('symbol')} (Order ID: {p.get('order_id')})")
                
                return positions
        else:
            logger.info(f"No existing positions file found, starting fresh")
            return []
    except Exception as e:
        logger.error(f"Error loading positions: {str(e)}")
        logger.error(traceback.format_exc())
        return []

def save_positions(positions):
    """Save current trading positions to JSON file"""
    try:
        with open(POSITIONS_FILE, 'w') as f:
            json.dump(positions, f, indent=4)
        logger.info(f"Saved {len(positions)} positions to {POSITIONS_FILE}")
    except Exception as e:
        logger.error(f"Error saving positions: {str(e)}")
        logger.error(traceback.format_exc())

# =================================================================
# Dhan API Functions
# =================================================================

def initialize_dhan_client(config):
    """Initialize the Dhan API client"""
    try:
        # Direct initialization with client_id and access_token
        logger.info(f"Initializing Dhan client with client_id: {config['client_id']}")
        dhan = dhanhq(config['client_id'], config['access_token'])
        logger.info("Dhan API client initialized successfully")
        
        # Test the connection
        try:
            orders = dhan.get_order_list()
            if isinstance(orders, dict) and 'status' in orders and orders['status'] == 'success':
                logger.info("Dhan API connection test successful")
            else:
                logger.info(f"Connection test returned: {orders}")
        except Exception as e:
            logger.warning(f"Connection test error: {str(e)}")
        
        return dhan
    except Exception as e:
        logger.error(f"Error initializing Dhan client: {str(e)}")
        logger.error(traceback.format_exc())
        return None

def get_security_id(symbol, security_ids_mapping):
    """Get security ID for a ticker symbol with enhanced diagnostics"""
    try:
        logger.info(f"SECURITY ID LOOKUP: Searching for {symbol}")
        
        # Create standardized versions of the symbol
        clean_symbol = symbol.replace('.NS', '')
        ns_symbol = clean_symbol + '.NS'
        
        # Try direct matches first
        logger.info(f"Trying exact match for '{symbol}'")
        if symbol in security_ids_mapping:
            security_id = security_ids_mapping[symbol]
            logger.info(f"FOUND EXACT MATCH: ID {security_id} for {symbol}")
            return security_id
            
        logger.info(f"Trying with .NS: '{ns_symbol}'")
        if ns_symbol in security_ids_mapping:
            security_id = security_ids_mapping[ns_symbol]
            logger.info(f"FOUND WITH .NS: ID {security_id} for {symbol} via {ns_symbol}")
            return security_id
            
        logger.info(f"Trying without .NS: '{clean_symbol}'")
        if clean_symbol in security_ids_mapping:
            security_id = security_ids_mapping[clean_symbol]
            logger.info(f"FOUND WITHOUT .NS: ID {security_id} for {symbol} via {clean_symbol}")
            return security_id
        
        # If we get here, we couldn't find the ID    
        logger.error(f"SECURITY ID NOT FOUND for {symbol}")
        
        # For debugging, dump some keys from the mapping
        sample_keys = list(security_ids_mapping.keys())[:20]
        logger.info(f"Sample security IDs available: {sample_keys}")
        
        # Try case-insensitive matching as last resort
        symbol_lower = clean_symbol.lower()
        for key, value in security_ids_mapping.items():
            if key.lower() == symbol_lower or key.lower().replace('.ns', '') == symbol_lower:
                logger.info(f"FOUND via case-insensitive match: ID {value} for {symbol} via {key}")
                return value
        
        # For better diagnosis, try to find any remotely similar keys
        similar_keys = [k for k in security_ids_mapping.keys() 
                      if clean_symbol.lower() in k.lower()]
        if similar_keys:
            logger.info(f"Similar keys found: {similar_keys}")
        
        return None
    except Exception as e:
        logger.error(f"Error getting security ID for {symbol}: {str(e)}")
        logger.error(traceback.format_exc())
        return None

def get_current_market_price(dhan, symbol, security_id=None):
    """Get the current market price for a symbol"""
    try:
        logger.info(f"Getting current market price for {symbol}")
        
        # Try to get quote using different methods
        try:
            # First try using the get_quote method with the symbol
            quote = dhan.get_quote(symbol)
            if isinstance(quote, dict) and 'last_traded_price' in quote:
                price = float(quote['last_traded_price'])
                logger.info(f"Got price for {symbol} using get_quote: {price}")
                return price
        except Exception as e:
            logger.info(f"Failed to get quote using symbol: {str(e)}")
        
        # If that fails, try using the get_ltp method with security_id
        if security_id:
            try:
                ltp = dhan.get_ltp(security_id, 'NSE')
                if isinstance(ltp, dict) and 'last_price' in ltp:
                    price = float(ltp['last_price'])
                    logger.info(f"Got price for {symbol} using get_ltp: {price}")
                    return price
            except Exception as e:
                logger.info(f"Failed to get LTP using security_id: {str(e)}")
        
        # As a fallback, try to find the price from the intraday candles
        try:
            candles = dhan.intraday_daily_minute_charts(security_id, 'NSE', 1)  # 1-minute candles
            if isinstance(candles, list) and len(candles) > 0:
                latest_candle = candles[-1]
                price = float(latest_candle['close_price'])
                logger.info(f"Got price for {symbol} from candle data: {price}")
                return price
        except Exception as e:
            logger.info(f"Failed to get price from candles: {str(e)}")
        
        logger.error(f"Could not get current market price for {symbol}")
        return None
    except Exception as e:
        logger.error(f"Error getting market price for {symbol}: {str(e)}")
        logger.error(traceback.format_exc())
        return None

def get_order_execution_price(dhan, order_id):
    """Get the execution price of an order"""
    try:
        logger.info(f"Getting execution price for order ID: {order_id}")
        
        # Get order details
        order_details = dhan.get_order_by_id(order_id)
        
        if isinstance(order_details, dict):
            # Check if order is executed
            if 'status' in order_details and order_details['status'] in ['COMPLETED', 'EXECUTED']:
                # Try to extract execution price
                if 'average_price' in order_details:
                    price = float(order_details['average_price'])
                    logger.info(f"Order {order_id} executed at price: {price}")
                    return price
                elif 'price' in order_details:
                    price = float(order_details['price'])
                    logger.info(f"Order {order_id} executed at price: {price}")
                    return price
            else:
                logger.warning(f"Order {order_id} not executed yet. Status: {order_details.get('status', 'unknown')}")
        else:
            logger.warning(f"Could not get details for order {order_id}")
        
        return None
    except Exception as e:
        logger.error(f"Error getting execution price for order {order_id}: {str(e)}")
        logger.error(traceback.format_exc())
        return None

def place_order(dhan, symbol, transaction_type, quantity, price=None, security_id=None):
    """Place an order through Dhan API with enhanced diagnostics"""
    try:
        logger.info(f"ORDER ATTEMPT: {transaction_type} {quantity} shares of {symbol}")
        
        if not security_id:
            logger.error(f"ORDER FAILED: No security ID provided for {symbol}")
            return None, None
            
        logger.info(f"Using security ID: {security_id}")
        
        # Get the correct transaction type constant from dhan
        dhan_transaction_type = dhan.BUY if transaction_type == 'BUY' else dhan.SELL
        
        # Place order
        order_params = {
            'security_id': security_id,
            'exchange_segment': dhan.NSE,
            'transaction_type': dhan_transaction_type,
            'quantity': quantity,
            'order_type': dhan.LIMIT if price is not None and price > 0 else dhan.MARKET,
            'product_type': dhan.INTRA,  # Intraday order
            'price': price if price is not None and price > 0 else 0
        }
        
        # Convert to a string representation for logging
        params_str = ", ".join([f"{k}: {v}" for k, v in order_params.items()])
        logger.info(f"ORDER PARAMS: {params_str}")
        
        # Detailed logging before API call
        logger.info(f"About to call dhan.place_order for {symbol}...")
        
        try:
            # Place the order
            response = dhan.place_order(**order_params)
            
            # Extended response logging
            logger.info(f"Response type: {type(response)}")
            
            # Log complete response with detailed error checking
            if isinstance(response, dict):
                try:
                    # Try to log the complete response as JSON
                    response_str = json.dumps(response, indent=2)
                    logger.info(f"COMPLETE ORDER RESPONSE:\n{response_str}")
                except:
                    # Fallback if not JSON serializable
                    logger.info(f"ORDER RESPONSE (non-serializable):")
                    for key, value in response.items():
                        logger.info(f"  Response[{key}] = {value}")
                        
                # Look for success/error indicators
                has_error = False
                error_message = None
                
                # Check status
                if 'status' in response:
                    status = response['status']
                    logger.info(f"Response status: {status}")
                    if status != 'success':
                        has_error = True
                        error_message = f"Status is {status}"
                
                # Check for explicit error messages
                error_keys = ['errorMessage', 'message', 'error', 'errorCode', 'errorMsg', 'remarks']
                for key in error_keys:
                    if key in response and response[key]:
                        logger.info(f"Response {key}: {response[key]}")
                        if not error_message:
                            error_message = response[key]
                            has_error = True
                
                if has_error:
                    logger.error(f"ORDER ERROR for {symbol}: {error_message or 'Unknown error'}")
            else:
                logger.info(f"Non-dict response: {response}")
        
        except Exception as place_error:
            logger.error(f"EXCEPTION DURING API CALL for {symbol}: {str(place_error)}")
            logger.error(traceback.format_exc())
            return None, None
        
        # Extract order ID if available
        order_id = None
        if isinstance(response, dict):
            # Try all possible paths for order ID
            if 'orderId' in response:
                order_id = response['orderId']
            elif 'order_id' in response:
                order_id = response['order_id']
            elif 'data' in response and isinstance(response['data'], dict):
                data = response['data']
                if 'orderId' in data:
                    order_id = data['orderId']
                elif 'order_id' in data:
                    order_id = data['order_id']
                
        if order_id:
            logger.info(f"SUCCESS: Got order ID {order_id} for {symbol}")
        else:
            logger.warning(f"WARNING: No order ID found in response for {symbol}")
            
            # Check if the response indicates success despite no order ID
            if isinstance(response, dict) and 'status' in response and response['status'] == 'success':
                logger.info(f"Response indicates success for {symbol} despite no order ID")
                order_id = f"unknown-{int(time.time())}"  # Generate a fallback ID
            else:
                logger.error(f"Order placement likely failed for {symbol}")
                return None, None
        
        return response, order_id
    except Exception as e:
        logger.error(f"ERROR placing order for {symbol}: {str(e)}")
        logger.error(traceback.format_exc())
        return None, None

def execute_order_with_retries(dhan, symbol, transaction_type, quantity, price, security_id, max_retries=3):
    """Place an order with retries and enhanced error handling"""
    logger.info(f"Executing {transaction_type} order for {quantity} shares of {symbol} with up to {max_retries} retries")
    
    retry_count = 0
    while retry_count <= max_retries:
        if retry_count > 0:
            logger.info(f"Retry {retry_count}/{max_retries} for {symbol}")
            time.sleep(5)  # Wait before retry
            
        # Attempt to place the order
        order_response, order_id = place_order(dhan, symbol, transaction_type, quantity, price, security_id)
        
        # Check if we got a valid response
        if order_response is not None and order_id is not None:
            logger.info(f"Order executed successfully for {symbol}, order ID: {order_id}")
            
            # Try to get the execution price
            execution_price = None
            
            # If it was a market order, try to get the current market price
            if price is None or price == 0:
                execution_price = get_current_market_price(dhan, symbol, security_id)
                if execution_price:
                    logger.info(f"Using current market price as execution price: {execution_price}")
                else:
                    logger.warning(f"Could not determine execution price for {symbol}")
            else:
                # For limit orders, use the limit price as execution price
                execution_price = price
                logger.info(f"Using limit price as execution price: {execution_price}")
            
            # Wait a bit and try to get the actual execution price from the order details
            if order_id and not order_id.startswith("unknown-"):
                logger.info(f"Waiting 2 seconds for order execution...")
                time.sleep(2)
                actual_price = get_order_execution_price(dhan, order_id)
                if actual_price:
                    execution_price = actual_price
                    logger.info(f"Updated with actual execution price: {execution_price}")
            
            return order_response, order_id, execution_price
            
        retry_count += 1
    
    logger.error(f"Order execution failed for {symbol} after {max_retries} retries")
    return None, None, None

# =================================================================
# Sector Analysis Functions
# =================================================================

def get_latest_sector_performance():
    """Read the latest sector performance data from sector.csv"""
    log_separator("READING SECTOR PERFORMANCE DATA")
    try:
        logger.info(f"Reading sector performance data from {SECTOR_PERFORMANCE_FILE}")
        
        if not os.path.exists(SECTOR_PERFORMANCE_FILE):
            logger.warning(f"Sector performance file {SECTOR_PERFORMANCE_FILE} not found")
            log_separator("SECTOR DATA READ FAILED")
            return None
            
        # Get file modification time
        mod_time = datetime.fromtimestamp(os.path.getmtime(SECTOR_PERFORMANCE_FILE))
        logger.info(f"File last modified: {mod_time.strftime('%Y-%m-%d %H:%M:%S')}")
            
        # Read the sector performance file
        df = pd.read_csv(SECTOR_PERFORMANCE_FILE)
        
        if df.empty:
            logger.warning("Sector performance file is empty")
            log_separator("SECTOR DATA READ FAILED")
            return None
            
        # Check if required columns exist
        required_columns = ['sector', 'sector_percent_change', 'is_positive']
        missing_columns = [col for col in required_columns if col not in df.columns]
        
        if missing_columns:
            logger.warning(f"Required columns missing in sector performance file: {missing_columns}")
            logger.info(f"Available columns: {df.columns.tolist()}")
            log_separator("SECTOR DATA READ FAILED")
            return None
        
        # Get the latest timestamp if available
        latest_time = None
        if 'timestamp' in df.columns:
            latest_time = df['timestamp'].max() if not df['timestamp'].empty else "unknown"
            logger.info(f"Latest timestamp in data: {latest_time}")
        
        # Log sector performance summary
        logger.info(f"Loaded data for {len(df)} sectors")
        
        # Log detailed sector performance for debugging
        logger.info("Sector performance details:")
        for _, row in df.iterrows():
            sector = row['sector']
            is_positive = bool(row['is_positive'])
            percent_change = float(row['sector_percent_change'])
            logger.info(f"  {sector}: {'POSITIVE' if is_positive else 'NEGATIVE'} ({percent_change:.2f}%)")
        
        log_separator("SECTOR DATA READ COMPLETE")
        return df
    
    except Exception as e:
        logger.error(f"Error reading sector performance data: {str(e)}")
        logger.error(traceback.format_exc())
        log_separator("SECTOR DATA READ FAILED")
        return None

def get_sector_for_ticker(symbol, sector_mapping):
    """Get sector for a ticker with robust handling of symbol variations"""
    # Try the exact symbol
    if symbol in sector_mapping:
        return sector_mapping[symbol]
        
    # Try without .NS suffix
    if symbol.endswith('.NS'):
        clean_symbol = symbol[:-3]
        if clean_symbol in sector_mapping:
            return sector_mapping[clean_symbol]
    
    # Try with .NS suffix
    if not symbol.endswith('.NS'):
        ns_symbol = symbol + '.NS'
        if ns_symbol in sector_mapping:
            return sector_mapping[ns_symbol]
    
    # Case-insensitive matching as last resort
    symbol_lower = symbol.lower().replace('.ns', '')
    for key, value in sector_mapping.items():
        if key.lower().replace('.ns', '') == symbol_lower:
            return value
    
    # Not found
    return None

def process_sector_data(dhan, sector_df, config, sector_mapping, positions, security_ids_mapping):
    """
    Process sector performance data to make trading decisions
    
    Args:
        dhan: Initialized Dhan API client
        sector_df: DataFrame with sector performance data
        config: Trading configuration
        sector_mapping: Mapping of tickers to sectors
        positions: Current positions
        security_ids_mapping: Mapping of symbols to security IDs
        
    Returns:
        Updated positions
    """
    log_separator("PROCESSING SECTOR DATA")
    if sector_df is None or sector_df.empty:
        logger.warning("No sector data available for processing")
        log_separator("SECTOR PROCESSING SKIPPED")
        return positions
    
    try:
        # Create a mapping of sectors to their performance
        sector_performances = {}
        for _, row in sector_df.iterrows():
            sector = row['sector']
            is_positive = bool(row['is_positive'])
            percent_change = float(row['sector_percent_change'])
            sector_performances[sector] = {
                'is_positive': is_positive,
                'percent_change': percent_change
            }
        
        logger.info(f"Processed performance data for {len(sector_performances)} sectors")
        
        # Process existing positions first
        logger.info("Processing existing positions for potential exits...")
        updated_positions = process_existing_positions(dhan, positions, sector_performances, security_ids_mapping)
        
        # Then look for new trading opportunities based on sector performance
        if config.get('place_new_orders', False):
            logger.info("Looking for new trading opportunities...")
            updated_positions = find_new_trading_opportunities(
                dhan, updated_positions, sector_performances, sector_mapping, config, security_ids_mapping
            )
        else:
            logger.info("Skipping new order opportunities (place_new_orders=False)")
        
        log_separator("SECTOR PROCESSING COMPLETE")
        return updated_positions
        
    except Exception as e:
        logger.error(f"Error processing sector data: {str(e)}")
        logger.error(traceback.format_exc())
        log_separator("SECTOR PROCESSING FAILED")
        return positions

def process_existing_positions(dhan, positions, sector_performances, security_ids_mapping):
    """
    Process existing positions to check if any need to be exited based on:
    1. Sector performance changes (sector turns negative for BUY, or positive for SELL)
    2. Stop loss price levels
    3. Target price levels
    
    Args:
        dhan: Initialized Dhan API client
        positions: List of current positions
        sector_performances: Dictionary of sector performances
        security_ids_mapping: Mapping of symbols to security IDs
        
    Returns:
        Updated positions
    """
    log_separator("PROCESSING EXISTING POSITIONS")
    if not positions:
        logger.info("No existing positions to process")
        log_separator("POSITION PROCESSING COMPLETE")
        return positions
        
    logger.info(f"Processing {len(positions)} existing positions")
    
    try:
        updated_positions = []
        squared_off_count = 0
        
        for position in positions:
            try:
                # Skip positions that are already closed
                if position.get('status') == 'CLOSED':
                    logger.info(f"Skipping already closed position for {position.get('symbol')}")
                    updated_positions.append(position)
                    continue
                    
                ticker = position['symbol']
                sector = position['sector']
                position_type = position['transaction_type']  # 'BUY' or 'SELL'
                
                logger.info(f"Checking position: {position_type} {ticker} (Sector: {sector})")
                
                # Get security ID
                security_id = get_security_id(ticker, security_ids_mapping)
                if not security_id:
                    logger.error(f"Could not find security ID for {ticker}. Skipping position check.")
                    updated_positions.append(position)
                    continue
                
                # Initialize exit flags
                exit_position = False
                exit_reason = ""
                
                # 1. Check for sector-based exit condition
                if sector in sector_performances:
                    sector_data = sector_performances[sector]
                    is_positive = sector_data['is_positive']
                    percent_change = sector_data['percent_change']
                    
                    logger.info(f"Sector {sector} is {'POSITIVE' if is_positive else 'NEGATIVE'} with {percent_change:.2f}% change")
                    
                    if position_type == 'BUY' and not is_positive:
                        # Exit BUY position if sector turned negative
                        exit_position = True
                        exit_reason = "Sector turned negative"
                        logger.info(f"Need to exit BUY position for {ticker} because sector turned negative")
                        
                    elif position_type == 'SELL' and is_positive:
                        # Exit SELL position if sector turned positive
                        exit_position = True
                        exit_reason = "Sector turned positive"
                        logger.info(f"Need to exit SELL position for {ticker} because sector turned positive")
                else:
                    logger.warning(f"No performance data available for sector {sector}")
                
                # 2. Check for price-based exit conditions (stop loss and target)
                # Get current market price
                current_price = get_current_market_price(dhan, ticker, security_id)
                
                if current_price:
                    logger.info(f"Current market price for {ticker}: {current_price}")
                    
                    # Check if we have an entry price
                    entry_price = position.get('entry_price')
                    if entry_price:
                        entry_price = float(entry_price)
                        
                        # Check for stop loss
                        if 'stop_loss_percent' in position and not exit_position:
                            stop_loss_percent = float(position['stop_loss_percent'])
                            
                            if position_type == 'BUY':
                                # For BUY positions, stop loss is below entry price
                                stop_loss_price = entry_price * (1 - stop_loss_percent/100)
                                logger.info(f"Stop loss for {ticker} BUY position: {stop_loss_price} (Entry: {entry_price}, SL%: {stop_loss_percent}%)")
                                
                                if current_price <= stop_loss_price:
                                    exit_position = True
                                    exit_reason = f"Stop loss triggered at {current_price} (Stop: {stop_loss_price})"
                                    logger.info(f"Stop loss triggered for {ticker} BUY position: Current: {current_price} <= Stop: {stop_loss_price}")
                            
                            elif position_type == 'SELL':
                                # For SELL positions, stop loss is above entry price
                                stop_loss_price = entry_price * (1 + stop_loss_percent/100)
                                logger.info(f"Stop loss for {ticker} SELL position: {stop_loss_price} (Entry: {entry_price}, SL%: {stop_loss_percent}%)")
                                
                                if current_price >= stop_loss_price:
                                    exit_position = True
                                    exit_reason = f"Stop loss triggered at {current_price} (Stop: {stop_loss_price})"
                                    logger.info(f"Stop loss triggered for {ticker} SELL position: Current: {current_price} >= Stop: {stop_loss_price}")
                        
                        # Check for target
                        if 'target_percent' in position and not exit_position:
                            target_percent = float(position['target_percent'])
                            
                            if position_type == 'BUY':
                                # For BUY positions, target is above entry price
                                target_price = entry_price * (1 + target_percent/100)
                                logger.info(f"Target for {ticker} BUY position: {target_price} (Entry: {entry_price}, Target%: {target_percent}%)")
                                
                                if current_price >= target_price:
                                    exit_position = True
                                    exit_reason = f"Target reached at {current_price} (Target: {target_price})"
                                    logger.info(f"Target reached for {ticker} BUY position: Current: {current_price} >= Target: {target_price}")
                            
                            elif position_type == 'SELL':
                                # For SELL positions, target is below entry price
                                target_price = entry_price * (1 - target_percent/100)
                                logger.info(f"Target for {ticker} SELL position: {target_price} (Entry: {entry_price}, Target%: {target_percent}%)")
                                
                                if current_price <= target_price:
                                    exit_position = True
                                    exit_reason = f"Target reached at {current_price} (Target: {target_price})"
                                    logger.info(f"Target reached for {ticker} SELL position: Current: {current_price} <= Target: {target_price}")
                    else:
                        logger.warning(f"No entry price available for {ticker}, cannot check stop loss/target")
                        
                        # Try to get and save the entry price for this position
                        if 'order_id' in position:
                            order_id = position['order_id']
                            if not order_id.startswith("unknown-"):
                                entry_price = get_order_execution_price(dhan, order_id)
                                if entry_price:
                                    logger.info(f"Retrieved entry price for {ticker}: {entry_price}")
                                    position['entry_price'] = entry_price
                                    
                                    # Also get current market price to save for future reference
                                    position['last_price'] = current_price
                else:
                    logger.warning(f"Could not get current market price for {ticker}")
                
                # If we need to exit the position
                if exit_position:
                    # Square off the position
                    opposite_type = 'SELL' if position_type == 'BUY' else 'BUY'
                    quantity = position['quantity']
                    
                    logger.info(f"Placing {opposite_type} order to exit position for {ticker}: {exit_reason}")
                    
                    # Place the exit order with retries
                    exit_order, exit_order_id, exit_price = execute_order_with_retries(
                        dhan,
                        ticker,
                        opposite_type,
                        quantity,
                        None,  # Market order
                        security_id,
                        max_retries=3
                    )
                    
                    if exit_order:
                        # Update position status
                        position['exit_time'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                        position['exit_reason'] = exit_reason
                        position['exit_order_id'] = exit_order_id or 'unknown'
                        position['status'] = 'CLOSED'
                        
                        # Save exit price if available
                        if exit_price:
                            position['exit_price'] = exit_price
                            
                            # Calculate P&L if both entry and exit prices are available
                            if 'entry_price' in position:
                                entry_price = float(position['entry_price'])
                                pnl = 0
                                
                                if position_type == 'BUY':
                                    # For BUY, profit = sell_price - buy_price
                                    pnl = (exit_price - entry_price) * position['quantity']
                                else:
                                    # For SELL, profit = buy_price - sell_price
                                    pnl = (entry_price - exit_price) * position['quantity']
                                    
                                position['pnl'] = pnl
                                logger.info(f"P&L for {ticker}: {pnl}")
                        
                        logger.info(f"Exited {position_type} position for {ticker}: {exit_reason}")
                        squared_off_count += 1
                    else:
                        logger.warning(f"Failed to place exit order for {ticker}")
                else:
                    # If we didn't exit but got a current price, update the position with it
                    if current_price:
                        position['last_price'] = current_price
                        logger.info(f"Updated last price for {ticker}: {current_price}")
                
                updated_positions.append(position)
                
            except Exception as e:
                logger.error(f"Error processing position for {position.get('symbol', 'unknown')}: {str(e)}")
                logger.error(traceback.format_exc())
                # Add the position anyway to avoid losing it
                updated_positions.append(position)
        
        if squared_off_count > 0:
            logger.info(f"Squared off {squared_off_count} positions")
        else:
            logger.info("No positions needed to be exited")
        
        log_separator("POSITION PROCESSING COMPLETE")
        return updated_positions
        
    except Exception as e:
        logger.error(f"Error processing existing positions: {str(e)}")
        logger.error(traceback.format_exc())
        log_separator("POSITION PROCESSING FAILED")
        return positions

def find_new_trading_opportunities(dhan, positions, sector_performances, sector_mapping, config, security_ids_mapping):
    """
    Find new trading opportunities based on sector performance
    
    Args:
        dhan: Initialized Dhan API client  
        positions: List of current positions
        sector_performances: Dictionary of sector performances
        sector_mapping: Mapping of tickers to sectors
        config: Trading configuration
        security_ids_mapping: Mapping of symbols to security IDs
        
    Returns:
        Updated positions
    """
    log_separator("FINDING NEW TRADING OPPORTUNITIES")
    
    try:
        # Get the tickers from the config
        tickers_config = config.get('tickers', [])
        if not tickers_config:
            logger.warning("No tickers found in configuration")
            log_separator("NEW OPPORTUNITIES SKIPPED")
            return positions
        
        # Get all active tickers (where active is true)
        active_tickers = [t for t in tickers_config if t.get('active', False)]
        logger.info(f"Found {len(active_tickers)} active tickers out of {len(tickers_config)} total")
        
        # Debug counters for each processing stage
        tickers_considered = 0
        tickers_with_sector_data = 0
        tickers_matching_strategy = 0
        tickers_with_security_id = 0
        tickers_ordered = 0
        
        # Process tickers in original order without prioritization
        ordered_tickers = active_tickers
        logger.info(f"Processing tickers in order: {[t['symbol'] for t in ordered_tickers]}")
        
        # Check if we already have positions in these tickers
        existing_position_tickers = [p['symbol'] for p in positions if p.get('status') != 'CLOSED']
        logger.info(f"Already have open positions for: {existing_position_tickers}")
        
        # Log all sector performances for reference
        logger.info("Current sector performances:")
        for sector, perf in sector_performances.items():
            is_positive = perf['is_positive']
            percent_change = perf['percent_change']
            logger.info(f"  Sector {sector}: {'POSITIVE' if is_positive else 'NEGATIVE'} ({percent_change:.2f}%)")
        
        new_positions_count = 0
        skipped_positions_count = 0
        error_positions_count = 0
        
        # Process each active ticker from the config
        for ticker_config in ordered_tickers:
            try:
                tickers_considered += 1
                symbol = ticker_config['symbol']
                
                logger.info(f"Processing ticker {tickers_considered}: {symbol}")
                
                # Skip if we already have an open position for this ticker
                if symbol in existing_position_tickers:
                    logger.info(f"Skipping {symbol} - already have an open position")
                    skipped_positions_count += 1
                    continue
                
                # Get the sector for this ticker
                sector = get_sector_for_ticker(symbol, sector_mapping)
                    
                if not sector:
                    logger.warning(f"Could not find sector for {symbol} in sector mapping")
                    skipped_positions_count += 1
                    continue
                    
                tickers_with_sector_data += 1
                logger.info(f"Found sector {sector} for {symbol}")
                    
                # Check if we have performance data for this sector
                if sector not in sector_performances:
                    logger.warning(f"No performance data for sector {sector}")
                    skipped_positions_count += 1
                    continue
                    
                # Get the sector performance
                sector_data = sector_performances[sector]
                is_positive = sector_data['is_positive']
                percent_change = sector_data['percent_change']
                
                logger.info(f"Evaluating {symbol} in sector {sector} ({'+' if is_positive else '-'}{abs(percent_change):.2f}%)")
                
                # Get ticker configuration
                transaction_type = ticker_config['transaction_type']
                quantity = ticker_config['quantity']
                stop_loss_percent = ticker_config.get('stop_loss_percent', 1.0)
                target_percent = ticker_config.get('target_percent', 1.0)
                entry_price = ticker_config.get('entry_price', '')
                
                # Determine if we should trade based on sector performance
                should_trade = False
                trade_reason = ""
                
                if transaction_type == 'BUY' and is_positive:
                    # Buy when sector is positive
                    should_trade = True
                    trade_reason = f"Positive sector performance: {percent_change:.2f}%"
                    logger.info(f"Should BUY {symbol} because sector {sector} is positive")
                    
                elif transaction_type == 'SELL' and not is_positive:
                    # Sell when sector is negative
                    should_trade = True
                    trade_reason = f"Negative sector performance: {percent_change:.2f}%"
                    logger.info(f"Should SELL {symbol} because sector {sector} is negative")
                else:
                    logger.info(f"Not trading {symbol} - sector performance doesn't match strategy")
                    logger.info(f"  Transaction type: {transaction_type}")
                    logger.info(f"  Sector is_positive: {is_positive}")
                    skipped_positions_count += 1
                
                if should_trade:
                    tickers_matching_strategy += 1
                    
                    # Get the security ID
                    security_id = get_security_id(symbol, security_ids_mapping)
                    
                    if not security_id:
                        logger.error(f"Could not find security ID for {symbol}. Skipping.")
                        skipped_positions_count += 1
                        continue
                        
                    tickers_with_security_id += 1
                    
                    # Place the order (market order if entry_price is empty)
                    price = None if entry_price == '' else float(entry_price)
                    
                    # Log trade decision
                    logger.info(f"Placing {transaction_type} order for {quantity} shares of {symbol}: {trade_reason}")
                    
                    # Place order using Dhan client with retries
                    order, order_id, execution_price = execute_order_with_retries(
                        dhan,
                        symbol,
                        transaction_type,
                        quantity,
                        price,
                        security_id,
                        max_retries=3
                    )
                    
                    if order:
                        tickers_ordered += 1
                        
                        # Create new position record
                        new_position = {
                            'symbol': symbol,
                            'sector': sector,
                            'transaction_type': transaction_type,
                            'quantity': quantity,
                            'entry_time': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                            'entry_reason': trade_reason,
                            'order_id': order_id or f"unknown-{int(time.time())}",
                            'stop_loss_percent': stop_loss_percent,
                            'target_percent': target_percent,
                            'status': 'OPEN'
                        }
                        
                        # Add execution price if available
                        if execution_price:
                            new_position['entry_price'] = execution_price
                        
                        # If we specified a price in the order, use that as the entry price
                        if price is not None:
                            new_position['entry_price'] = price
                        
                        positions.append(new_position)
                        existing_position_tickers.append(symbol)
                        new_positions_count += 1
                        
                        logger.info(f"New {transaction_type} position for {symbol}: {trade_reason}")
                        
                        # Add a delay between orders to avoid rate limiting
                        if new_positions_count < len(ordered_tickers):  # Don't wait after last order
                            wait_time = 10  # 10 seconds between orders
                            logger.info(f"Waiting {wait_time} seconds before next order to avoid rate limiting...")
                            time.sleep(wait_time)
                    else:
                        logger.error(f"Failed to place order for {symbol}")
                        error_positions_count += 1
            
            except Exception as e:
                logger.error(f"Error processing ticker {ticker_config.get('symbol', 'unknown')}: {str(e)}")
                logger.error(traceback.format_exc())
                error_positions_count += 1
        
        # Log summary
        logger.info(f"Ticker processing summary:")
        logger.info(f"  Total tickers considered: {tickers_considered}")
        logger.info(f"  Tickers with sector data: {tickers_with_sector_data}")
        logger.info(f"  Tickers matching strategy: {tickers_matching_strategy}")
        logger.info(f"  Tickers with security ID: {tickers_with_security_id}")
        logger.info(f"  Orders successfully placed: {tickers_ordered}")
        
        logger.info(f"New positions added: {new_positions_count}")
        logger.info(f"Positions skipped: {skipped_positions_count}")
        logger.info(f"Positions with errors: {error_positions_count}")
        
        if new_positions_count > 0:
            logger.info(f"Added {new_positions_count} new positions based on sector performance")
        
        log_separator("NEW OPPORTUNITIES PROCESSING COMPLETE")
        return positions
    
    except Exception as e:
        logger.error(f"Error finding new trading opportunities: {str(e)}")
        logger.error(traceback.format_exc())
        log_separator("NEW OPPORTUNITIES PROCESSING FAILED")
        return positions

def summarize_current_positions(positions):
    """Print a summary of current positions"""
    log_separator("POSITIONS SUMMARY")
    try:
        # Count positions by type and status
        open_buy = sum(1 for p in positions if p.get('transaction_type') == 'BUY' and p.get('status') == 'OPEN')
        open_sell = sum(1 for p in positions if p.get('transaction_type') == 'SELL' and p.get('status') == 'OPEN')
        closed = sum(1 for p in positions if p.get('status') == 'CLOSED')
        
        logger.info("Current positions summary:")
        logger.info(f"  Open BUY positions: {open_buy}")
        logger.info(f"  Open SELL positions: {open_sell}")
        logger.info(f"  Closed positions: {closed}")
        logger.info(f"  Total positions: {len(positions)}")
        
        # Print open positions
        if open_buy + open_sell > 0:
            logger.info("Open positions:")
            open_positions = [p for p in positions if p.get('status') == 'OPEN']
            
            for position in open_positions:
                ticker = position['symbol']
                pos_type = position['transaction_type']
                sector = position['sector']
                entry_time = position['entry_time']
                order_id = position.get('order_id', 'unknown')
                
                position_details = [
                    f"Entry: {entry_time}",
                    f"Order ID: {order_id}"
                ]
                
                if 'entry_price' in position:
                    position_details.append(f"Entry Price: {position['entry_price']}")
                
                if 'last_price' in position:
                    position_details.append(f"Last Price: {position['last_price']}")
                
                if 'stop_loss_percent' in position:
                    position_details.append(f"SL%: {position['stop_loss_percent']}%")
                
                if 'target_percent' in position:
                    position_details.append(f"Target%: {position['target_percent']}%")
                
                position_str = f"  {pos_type} {ticker} (Sector: {sector}, {', '.join(position_details)})"
                logger.info(position_str)
                
        # Calculate total P&L for closed positions
        closed_positions = [p for p in positions if p.get('status') == 'CLOSED']
        if closed_positions:
            total_pnl = sum(float(p.get('pnl', 0)) for p in closed_positions)
            logger.info(f"Total P&L for closed positions: {total_pnl}")
            
            # List recent closed positions
            logger.info("Recently closed positions:")
            # Sort by exit_time, most recent first
            recent_closed = sorted(
                closed_positions, 
                key=lambda p: p.get('exit_time', ''), 
                reverse=True
            )[:5]  # Show last 5
            
            for position in recent_closed:
                ticker = position['symbol']
                pos_type = position['transaction_type']
                exit_reason = position.get('exit_reason', 'Unknown')
                exit_time = position.get('exit_time', 'Unknown')
                pnl = position.get('pnl', 'Unknown')
                
                logger.info(f"  {pos_type} {ticker} - Closed at {exit_time}, Reason: {exit_reason}, P&L: {pnl}")
        
        log_separator("POSITIONS SUMMARY COMPLETE")
    except Exception as e:
        logger.error(f"Error summarizing positions: {str(e)}")
        logger.error(traceback.format_exc())
        log_separator("POSITIONS SUMMARY FAILED")

# =================================================================
# Main Program Logic
# =================================================================

def main():
    """Main program execution"""
    try:
        log_separator("PROGRAM START")
        logger.info("==========================================")
        logger.info("Starting Dhan Sector-Based Trading Program")
        logger.info("==========================================")
        
        # Log current time
        current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        logger.info(f"Current time: {current_time}")
        
        # Step 1: Load configuration
        logger.info("Step 1: Loading trading configuration...")
        config = load_config()
        
        if not config:
            logger.error("Failed to load trading configuration. Exiting.")
            log_separator("PROGRAM TERMINATED")
            return
            
        # Step 2: Initialize Dhan client
        logger.info("Step 2: Initializing Dhan API client...")
        dhan = initialize_dhan_client(config)
        
        if not dhan:
            logger.error("Failed to initialize Dhan API client. Exiting.")
            log_separator("PROGRAM TERMINATED")
            return
            
        # Step 3: Load sector mapping
        logger.info("Step 3: Loading sector mapping...")
        sector_mapping = load_sector_mapping()
        
        if not sector_mapping:
            logger.error("Failed to load sector mapping. Exiting.")
            log_separator("PROGRAM TERMINATED")
            return
            
        # Step 4: Load security IDs mapping from Excel
        logger.info("Step 4: Loading security IDs mapping from Excel...")
        security_ids_mapping = load_security_ids()
        
        if not security_ids_mapping:
            logger.error("Failed to load security IDs mapping. Cannot place orders without security IDs.")
            log_separator("PROGRAM TERMINATED")
            return
            
        # Step 4.5: Validate security IDs for all configured tickers
        logger.info("Step 4.5: Validating security IDs for active tickers...")
        validation_results = validate_security_ids(security_ids_mapping, config)
        
        if validation_results and validation_results["missing"]:
            logger.warning(f"Some tickers are missing security IDs: {validation_results['missing']}")
            logger.warning("These tickers will be skipped during trading!")
        
        # Step 5: Load existing positions
        logger.info("Step 5: Loading existing positions...")
        positions = load_positions()
        
        # Step 6: Main trading loop
        check_interval = config.get('check_interval_seconds', DEFAULT_CHECK_INTERVAL)
        logger.info(f"Step 6: Starting trading loop (check interval: {check_interval} seconds)...")
        
        try:
            cycle_count = 0
            while True:
                cycle_count += 1
                log_separator(f"TRADING CYCLE {cycle_count}")
                current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                logger.info(f"Trading cycle {cycle_count} started at {current_time}")
                
                # Get the latest sector performance data
                sector_df = get_latest_sector_performance()
                
                if sector_df is not None:
                    # Process sector data for trading decisions
                    positions = process_sector_data(dhan, sector_df, config, sector_mapping, positions, security_ids_mapping)
                    
                    # Save updated positions
                    save_positions(positions)
                    
                    # Print summary of current positions
                    summarize_current_positions(positions)
                else:
                    logger.warning("No sector data available, skipping this cycle")
                
                # Log cycle completion
                logger.info(f"Trading cycle {cycle_count} completed")
                
                # Wait for the next check interval
                next_check_time = (datetime.now() + pd.Timedelta(seconds=check_interval)).strftime('%H:%M:%S')
                logger.info(f"Waiting {check_interval} seconds until next check at {next_check_time}...")
                log_separator(f"CYCLE {cycle_count} COMPLETE")
                time.sleep(check_interval)
        
        except KeyboardInterrupt:
            logger.info("Trading program stopped by user")
            # Save positions before exiting
            save_positions(positions)
            log_separator("PROGRAM TERMINATED BY USER")
        
    except Exception as e:
        logger.error(f"Critical error in main program: {str(e)}")
        logger.error(traceback.format_exc())
        log_separator("PROGRAM TERMINATED DUE TO ERROR")

if __name__ == "__main__":
    main()