# app/config.py
import os
from pathlib import Path

# Project directories
BASE_DIR = Path(__file__).parent.parent.absolute()
OUTPUT_DIR = os.path.join(BASE_DIR, "output")
DATA_DIR = os.path.join(OUTPUT_DIR, "data")
PLOTS_DIR = os.path.join(OUTPUT_DIR, "plots")

# Create directories if they don't exist
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(PLOTS_DIR, exist_ok=True)

# Sector mapping for stocks
SECTOR_MAPPING = {
    # NIFTY METAL
    "NATIONALUM.NS": "NIFTY_METAL",
    "SAIL.NS": "NIFTY_METAL",
    "HINDALCO.NS": "NIFTY_METAL",
    "TATASTEEL.NS": "NIFTY_METAL",
    "JSL.NS": "NIFTY_METAL",
    "VEDL.NS": "NIFTY_METAL",
    "NMDC.NS": "NIFTY_METAL",
    "APLAPOLLO.NS": "NIFTY_METAL",
    "COALINDIA.NS": "NIFTY_METAL",
    "JINDALSTEL.NS": "NIFTY_METAL",
    "JSWSTEEL.NS": "NIFTY_METAL",
    "HINDCOPPER.NS": "NIFTY_METAL",
    "ADANIENT.NS": "NIFTY_METAL",
    "HINDZINC.NS": "NIFTY_METAL",
    "MOIL.NS": "NIFTY_METAL",
    "RATNAMANI.NS": "NIFTY_METAL",
    "WELCORP.NS": "NIFTY_METAL",
    
    # NIFTY CONSUMER DURABLES
    "DIXON.NS": "NIFTY_CONSR_DURBL",
    "ORIENTELEC.NS": "NIFTY_CONSR_DURBL",
    "AMBER.NS": "NIFTY_CONSR_DURBL",
    "HAVELLS.NS": "NIFTY_CONSR_DURBL",
    "TTKPRESTIG.NS": "NIFTY_CONSR_DURBL",
    "WHIRLPOOL.NS": "NIFTY_CONSR_DURBL",
    "RELAXO.NS": "NIFTY_CONSR_DURBL",
    "RAJESHEXPO.NS": "NIFTY_CONSR_DURBL",
    "KAJARIACER.NS": "NIFTY_CONSR_DURBL",
    "TITAN.NS": "NIFTY_CONSR_DURBL",
    "CROMPTON.NS": "NIFTY_CONSR_DURBL",
    "BLUESTARCO.NS": "NIFTY_CONSR_DURBL",
    "VGUARD.NS": "NIFTY_CONSR_DURBL",
    "BATAINDIA.NS": "NIFTY_CONSR_DURBL",
    "VOLTAS.NS": "NIFTY_CONSR_DURBL",
    
    # NIFTY ENERGY
    "ADANIGREEN.NS": "NIFTY_ENERGY",
    "ONGC.NS": "NIFTY_ENERGY",
    "POWERGRID.NS": "NIFTY_ENERGY",
    "NTPC.NS": "NIFTY_ENERGY",
    "RELIANCE.NS": "NIFTY_ENERGY",
    "BPCL.NS": "NIFTY_ENERGY",
    "TATAPOWER.NS": "NIFTY_ENERGY",
    "GAIL.NS": "NIFTY_ENERGY",
    "ADANIENSOL.NS": "NIFTY_ENERGY",
    "IOC.NS": "NIFTY_ENERGY",
    
    # NIFTY PHARMA
    "LAURUSLABS.NS": "NIFTY_PHARMA",
    "STAR.NS": "NIFTY_PHARMA",
    "GRANULES.NS": "NIFTY_PHARMA",
    "NATCOPHARM.NS": "NIFTY_PHARMA",
    "DIVISLAB.NS": "NIFTY_PHARMA",
    "BIOCON.NS": "NIFTY_PHARMA",
    "CIPLA.NS": "NIFTY_PHARMA",
    "ZYDUSLIFE.NS": "NIFTY_PHARMA",
    "IPCALAB.NS": "NIFTY_PHARMA",
    "SANOFI.NS": "NIFTY_PHARMA",
    "LUPIN.NS": "NIFTY_PHARMA",
    "AUROPHARMA.NS": "NIFTY_PHARMA",
    "SUNPHARMA.NS": "NIFTY_PHARMA",
    "ABBOTINDIA.NS": "NIFTY_PHARMA",
    "DRREDDY.NS": "NIFTY_PHARMA",
    "PFIZER.NS": "NIFTY_PHARMA",
    "ALKEM.NS": "NIFTY_PHARMA",
    "APLLTD.NS": "NIFTY_PHARMA",
    "GLENMARK.NS": "NIFTY_PHARMA",
    "GLAND.NS": "NIFTY_PHARMA",
    "TORNTPHARM.NS": "NIFTY_PHARMA",
    "SYNGENE.NS": "NIFTY_PHARMA",
    "METROPOLIS.NS": "NIFTY_PHARMA",
    "LALPATHLAB.NS": "NIFTY_PHARMA",
    "MAXHEALTH.NS": "NIFTY_PHARMA",
    "APOLLOHOSP.NS": "NIFTY_PHARMA",
    
    # NIFTY OIL AND GAS
    "GSPL.NS": "NIFTY_OIL_AND_GAS",
    "GUJGASLTD.NS": "NIFTY_OIL_AND_GAS",
    "JIOFIN.NS": "NIFTY_OIL_AND_GAS",
    "ONGC.NS": "NIFTY_OIL_AND_GAS",
    "RELIANCE.NS": "NIFTY_OIL_AND_GAS",
    "OIL.NS": "NIFTY_OIL_AND_GAS",
    "MGL.NS": "NIFTY_OIL_AND_GAS",
    "ATGL.NS": "NIFTY_OIL_AND_GAS",
    "BPCL.NS": "NIFTY_OIL_AND_GAS",
    "GAIL.NS": "NIFTY_OIL_AND_GAS",
    "CASTROLIND.NS": "NIFTY_OIL_AND_GAS",
    "HINDPETRO.NS": "NIFTY_OIL_AND_GAS",
    "IOC.NS": "NIFTY_OIL_AND_GAS",
    "IGL.NS": "NIFTY_OIL_AND_GAS",
    "PETRONET.NS": "NIFTY_OIL_AND_GAS",
    "AEGISLOG.NS": "NIFTY_OIL_AND_GAS",
    
    # NIFTY AUTO
    "SONACOMS.NS": "NIFTY_AUTO",
    "MOTHERSON.NS": "NIFTY_AUTO",
    "MRF.NS": "NIFTY_AUTO",
    "BHARATFORG.NS": "NIFTY_AUTO",
    "BAJAJ-AUTO.NS": "NIFTY_AUTO",
    "BAJAJAUTO.NS": "NIFTY_AUTO",
    "BALKRISIND.NS": "NIFTY_AUTO",
    "M&M.NS": "NIFTY_AUTO",
    "TATAMOTORS.NS": "NIFTY_AUTO",
    "ASHOKLEY.NS": "NIFTY_AUTO",
    "EICHERMOT.NS": "NIFTY_AUTO",
    "TVSMOTOR.NS": "NIFTY_AUTO",
    "HEROMOTOCO.NS": "NIFTY_AUTO",
    "EXIDEIND.NS": "NIFTY_AUTO",
    "MARUTI.NS": "NIFTY_AUTO",
    "ARE&M.NS": "NIFTY_AUTO",
    "BOSCHLTD.NS": "NIFTY_AUTO",
    "TIINDIA.NS": "NIFTY_AUTO",
    
    # NIFTY FINANCIAL SERVICES
    "HDFCAMC.NS": "NIFTY_FIN_SERVICE",
    "RECLTD.NS": "NIFTY_FIN_SERVICE",
    "CHOLAFIN.NS": "NIFTY_FIN_SERVICE",
    "KOTAKBANK.NS": "NIFTY_FIN_SERVICE",
    "SBILIFE.NS": "NIFTY_FIN_SERVICE",
    "BAJAJFINSV.NS": "NIFTY_FIN_SERVICE",
    "HDFCBANK.NS": "NIFTY_FIN_SERVICE",
    "M&MFIN.NS": "NIFTY_FIN_SERVICE",
    "BAJFINANCE.NS": "NIFTY_FIN_SERVICE",
    "PEL.NS": "NIFTY_FIN_SERVICE",
    "PFC.NS": "NIFTY_FIN_SERVICE",
    "SBIN.NS": "NIFTY_FIN_SERVICE",
    "IEX.NS": "NIFTY_FIN_SERVICE",
    "ICICIBANK.NS": "NIFTY_FIN_SERVICE",
    "AXISBANK.NS": "NIFTY_FIN_SERVICE",
    "HDFCLIFE.NS": "NIFTY_FIN_SERVICE",
    "ICICIPRULI.NS": "NIFTY_FIN_SERVICE",
    "ICICIGI.NS": "NIFTY_FIN_SERVICE",
    "MUTHOOTFIN.NS": "NIFTY_FIN_SERVICE",

    # NIFTY FINSERV25-50
    "SHRIRAMFIN.NS": "NIFTY_FINSERV25_50",
    "SBICARD.NS": "NIFTY_FINSERV25_50",
    "LICHSGFIN.NS": "NIFTY_FINSERV25_50",
    
    # NIFTY MEDIA
    "PVRINOX.NS": "NIFTY_MEDIA",
    "DISHTV.NS": "NIFTY_MEDIA",
    "SAREGAMA.NS": "NIFTY_MEDIA",
    "SUNTV.NS": "NIFTY_MEDIA",
    "NETWORK18.NS": "NIFTY_MEDIA",
    "HATHWAY.NS": "NIFTY_MEDIA",
    "ZEEL.NS": "NIFTY_MEDIA",
    "NAZARA.NS": "NIFTY_MEDIA",
    
    # NIFTY PRIVATE BANKS
    "CUB.NS": "NIFTY_PVT_BANK",
    "RBLBANK.NS": "NIFTY_PVT_BANK",
    "KOTAKBANK.NS": "NIFTY_PVT_BANK",
    "HDFCBANK.NS": "NIFTY_PVT_BANK",
    "BANDHANBNK.NS": "NIFTY_PVT_BANK",
    "INDUSINDBK.NS": "NIFTY_PVT_BANK",
    "IDFCFIRSTB.NS": "NIFTY_PVT_BANK",
    "ICICIBANK.NS": "NIFTY_PVT_BANK",
    "AXISBANK.NS": "NIFTY_PVT_BANK",
    "FEDERALBNK.NS": "NIFTY_PVT_BANK",
    
    # NIFTY HEALTHCARE
    "LALPATHLAB.NS": "NIFTY_HEALTHCARE",
    "SYNGENE.NS": "NIFTY_HEALTHCARE",
    "METROPOLIS.NS": "NIFTY_HEALTHCARE",
    "APOLLOHOSP.NS": "NIFTY_HEALTHCARE",
    "MAXHEALTH.NS": "NIFTY_HEALTHCARE",
    
    # NIFTY BANK
    "KOTAKBANK.NS": "NIFTY_BANK",
    "CANBK.NS": "NIFTY_BANK",
    "HDFCBANK.NS": "NIFTY_BANK",
    "INDUSINDBK.NS": "NIFTY_BANK",
    "SBIN.NS": "NIFTY_BANK",
    "IDFCFIRSTB.NS": "NIFTY_BANK",
    "BANKBARODA.NS": "NIFTY_BANK",
    "ICICIBANK.NS": "NIFTY_BANK",
    "AXISBANK.NS": "NIFTY_BANK",
    "AUBANK.NS": "NIFTY_BANK",
    "PNB.NS": "NIFTY_BANK",
    "FEDERALBNK.NS": "NIFTY_BANK",
    
    # NIFTY CONSUMPTION
    "DIXON.NS": "NIFTY_CONSUMPTION",
    "ORIENTELEC.NS": "NIFTY_CONSUMPTION",
    "AMBER.NS": "NIFTY_CONSUMPTION",
    "HAVELLS.NS": "NIFTY_CONSUMPTION",
    "TTKPRESTIG.NS": "NIFTY_CONSUMPTION",
    "WHIRLPOOL.NS": "NIFTY_CONSUMPTION",
    "RELAXO.NS": "NIFTY_CONSUMPTION",
    "RAJESHEXPO.NS": "NIFTY_CONSUMPTION",
    "KAJARIACER.NS": "NIFTY_CONSUMPTION",
    "TITAN.NS": "NIFTY_CONSUMPTION",
    "CROMPTON.NS": "NIFTY_CONSUMPTION",
    "BLUESTARCO.NS": "NIFTY_CONSUMPTION",
    "VGUARD.NS": "NIFTY_CONSUMPTION",
    "BATAINDIA.NS": "NIFTY_CONSUMPTION",
    "VOLTAS.NS": "NIFTY_CONSUMPTION",
    
    # NIFTY PSU BANK
    "CANBK.NS": "NIFTY_PSU_BANK",
    "CENTRALBK.NS": "NIFTY_PSU_BANK",
    "INDIANB.NS": "NIFTY_PSU_BANK",
    "SBIN.NS": "NIFTY_PSU_BANK",
    "BANKINDIA.NS": "NIFTY_PSU_BANK",
    "BANKBARODA.NS": "NIFTY_PSU_BANK",
    "UNIONBANK.NS": "NIFTY_PSU_BANK",
    "UCOBANK.NS": "NIFTY_PSU_BANK",
    "MAHABANK.NS": "NIFTY_PSU_BANK",
    "PNB.NS": "NIFTY_PSU_BANK",
    "J&KBANK.NS": "NIFTY_PSU_BANK",
    "IOB.NS": "NIFTY_PSU_BANK",
    
    # NIFTY REALTY
    "SUNTECK.NS": "NIFTY_REALTY",
    "PRESTIGE.NS": "NIFTY_REALTY",
    "OBEROIRLTY.NS": "NIFTY_REALTY",
    "BRIGADE.NS": "NIFTY_REALTY",
    "DLF.NS": "NIFTY_REALTY",
    "SOBHA.NS": "NIFTY_REALTY",
    "LODHA.NS": "NIFTY_REALTY",
    "EMBDL.NS": "NIFTY_REALTY",
    "PHOENIXLTD.NS": "NIFTY_REALTY",
    "GODREJPROP.NS": "NIFTY_REALTY",
    
    # NIFTY CONSUMER
    "MARICO.NS": "NIFTY_CONSUMER",
    "UNITDSPR.NS": "NIFTY_CONSUMER",
    "RADICO.NS": "NIFTY_CONSUMER",
    "EMAMILTD.NS": "NIFTY_CONSUMER",
    "ITC.NS": "NIFTY_CONSUMER",
    "VBL.NS": "NIFTY_CONSUMER",
    "UBL.NS": "NIFTY_CONSUMER",
    "TATACONSUM.NS": "NIFTY_CONSUMER",
    "NESTLEIND.NS": "NIFTY_CONSUMER",
    "HINDUNILVR.NS": "NIFTY_CONSUMER",
    "BRITANNIA.NS": "NIFTY_CONSUMER",
    "COLPAL.NS": "NIFTY_CONSUMER",
    "PGHH.NS": "NIFTY_CONSUMER",
    "DABUR.NS": "NIFTY_CONSUMER",
    "GODREJCP.NS": "NIFTY_CONSUMER",
    
    # NIFTY IT
    "LTIM.NS": "NIFTY_IT",
    "PERSISTENT.NS": "NIFTY_IT",
    "MPHASIS.NS": "NIFTY_IT",
    "WIPRO.NS": "NIFTY_IT",
    "LTTS.NS": "NIFTY_IT",
    "HCLTECH.NS": "NIFTY_IT",
    "TECHM.NS": "NIFTY_IT",
    "INFY.NS": "NIFTY_IT",
    "COFORGE.NS": "NIFTY_IT",
    "TCS.NS": "NIFTY_IT"
}

# Updated TOP_STOCKS list with all stocks from paste-2.txt
TOP_STOCKS = [
    {"symbol": "ABB", "name": "ABB", "sector": "FMCG"},
    {"symbol": "LAURUSLABS", "name": "Lauruslabs", "sector": "Pharmaceuticals"},
    {"symbol": "BAJFINANCE", "name": "Bajfinance", "sector": "Finance"},
    {"symbol": "BEL", "name": "BEL", "sector": "Aerospace & Defence"},
    {"symbol": "BLUESTARCO", "name": "Bluestarco", "sector": "FMCG"},
    {"symbol": "CESC", "name": "CESC", "sector": "Miscellaneous"},
    {"symbol": "CHAMBLFERT", "name": "Chamblfert", "sector": "Industrials"},
    {"symbol": "EXIDEIND", "name": "Exideind", "sector": "Auto"},
    {"symbol": "CIPLA", "name": "Cipla", "sector": "Pharmaceuticals"},
    {"symbol": "CGPOWER", "name": "CGPower", "sector": "FMCG"},
    {"symbol": "DABUR", "name": "Dabur", "sector": "FMCG"},
    {"symbol": "BHEL", "name": "BHEL", "sector": "FMCG"},
    {"symbol": "HINDPETRO", "name": "Hindpetro", "sector": "Industrials"},
    {"symbol": "SBIN", "name": "Sbin", "sector": "Bank"},
    {"symbol": "SAIL", "name": "Sail", "sector": "Metals"},
    {"symbol": "TITAN", "name": "Titan", "sector": "Miscellaneous"},
    {"symbol": "DRREDDY", "name": "Drreddy", "sector": "Pharmaceuticals"},
    {"symbol": "HDFCBANK", "name": "Hdfcbank", "sector": "Bank"},
    {"symbol": "HEROMOTOCO", "name": "Heromotoco", "sector": "Auto"},
    {"symbol": "HFCL", "name": "HFCL", "sector": "Telecom"},
    {"symbol": "HINDZINC", "name": "Hindzinc", "sector": "Metals"},
    {"symbol": "INFY", "name": "Infy", "sector": "I.T"},
    {"symbol": "JSWSTEEL", "name": "Jswsteel", "sector": "Metals"},
    {"symbol": "KOTAKBANK", "name": "Kotakbank", "sector": "Bank"},
    {"symbol": "TRENT", "name": "Trent", "sector": "FMCG"},
    {"symbol": "LICHSGFIN", "name": "Lichsgfin", "sector": "Finance"},
    {"symbol": "LUPIN", "name": "Lupin", "sector": "Pharmaceuticals"},
    {"symbol": "MFSL", "name": "MFSL", "sector": "Finance"},
    {"symbol": "NCC", "name": "NCC", "sector": "Realty"},
    {"symbol": "VEDL", "name": "Vedl", "sector": "Industrials"},
    {"symbol": "GRASIM", "name": "Grasim", "sector": "Miscellaneous"},
    {"symbol": "PEL", "name": "Pel", "sector": "Finance"},
    {"symbol": "ONGC", "name": "Ongc", "sector": "Oils"},
    {"symbol": "RELIANCE", "name": "Reliance", "sector": "Industrials"},
    {"symbol": "PIDILITIND", "name": "Pidilitind", "sector": "Industrials"},
    {"symbol": "PATANJALI", "name": "Patanjali", "sector": "FMCG"},
    {"symbol": "SHREECEM", "name": "Shreecem", "sector": "Industrials"},
    {"symbol": "TATAPOWER", "name": "Tatapower", "sector": "Miscellaneous"},
    {"symbol": "TATAELXSI", "name": "Tataelxsi", "sector": "I.T"},
    {"symbol": "ACC", "name": "ACC", "sector": "Industrials"},
    {"symbol": "TORNTPHARM", "name": "Torntpharm", "sector": "Pharmaceuticals"},
    {"symbol": "AMBUJACEM", "name": "Ambujacem", "sector": "Industrials"},
    {"symbol": "HINDALCO", "name": "Hindalco", "sector": "Metals"},
    {"symbol": "FEDERALBNK", "name": "Federalbnk", "sector": "Bank"},
    {"symbol": "TATASTEEL", "name": "Tatasteel", "sector": "Metals"},
    {"symbol": "ASHOKLEY", "name": "Ashokley", "sector": "Auto"},
    {"symbol": "CUMMINSIND", "name": "Cumminsind", "sector": "FMCG"},
    {"symbol": "TATACOMM", "name": "Tatacomm", "sector": "Telecom"},
    {"symbol": "BHARATFORG", "name": "Bharatforg", "sector": "Industrials"},
    {"symbol": "LT", "name": "LT", "sector": "Realty"},
    {"symbol": "M&M", "name": "M&M", "sector": "Auto"},
    {"symbol": "BOSCHLTD", "name": "Boschltd", "sector": "Auto"},
    {"symbol": "BPCL", "name": "Bpcl", "sector": "Industrials"},
    {"symbol": "SIEMENS", "name": "Siemens", "sector": "FMCG"},
    {"symbol": "TATAMOTORS", "name": "Tatamotors", "sector": "Auto"},
    {"symbol": "VOLTAS", "name": "Voltas", "sector": "FMCG"},
    {"symbol": "HINDUNILVR", "name": "Hindunilvr", "sector": "FMCG"},
    {"symbol": "TATACHEM", "name": "Tatachem", "sector": "Industrials"},
    {"symbol": "NESTLEIND", "name": "Nestleind", "sector": "FMCG"},
    {"symbol": "TATACONSUM", "name": "Tataconsum", "sector": "FMCG"},
    {"symbol": "ASIANPAINT", "name": "Asianpaint", "sector": "Industrials"},
    {"symbol": "BRITANNIA", "name": "Britannia", "sector": "FMCG"},
    {"symbol": "COLPAL", "name": "Colpal", "sector": "FMCG"},
    {"symbol": "INDHOTEL", "name": "Indhotel", "sector": "Services"},
    {"symbol": "ITC", "name": "Itc", "sector": "FMCG"},
    {"symbol": "BALKRISIND", "name": "Balkrisind", "sector": "Auto"},
    {"symbol": "PHOENIXLTD", "name": "Phoenixltd", "sector": "Realty"},
    {"symbol": "SRF", "name": "SRF", "sector": "Industrials"},
    {"symbol": "EICHERMOT", "name": "Eichermot", "sector": "Auto"},
    {"symbol": "WIPRO", "name": "Wipro", "sector": "I.T"},
    {"symbol": "APOLLOHOSP", "name": "Apollohosp", "sector": "Pharmaceuticals"},
    {"symbol": "SUPREMEIND", "name": "Supremeind", "sector": "FMCG"},
    {"symbol": "SHRIRAMFIN", "name": "Shriramfin", "sector": "Finance"},
    {"symbol": "CHOLAFIN", "name": "Cholafin", "sector": "Finance"},
    {"symbol": "UPL", "name": "UPL", "sector": "Industrials"},
    {"symbol": "ADANIENT", "name": "Adanient", "sector": "Services"},
    {"symbol": "LICI", "name": "LICI", "sector": "Services"},
    {"symbol": "DELHIVERY", "name": "Delhivery", "sector": "Services"},
    {"symbol": "HINDCOPPER", "name": "Hindcopper", "sector": "Metals"},
    {"symbol": "MOTHERSON", "name": "Motherson", "sector": "Auto"},
    {"symbol": "HAVELLS", "name": "Havells", "sector": "FMCG"},
    {"symbol": "PPLPHARMA", "name": "PPLPharma", "sector": "Pharmaceuticals"},
    {"symbol": "KEI", "name": "KEI", "sector": "Industrials"},
    {"symbol": "KAYNES", "name": "Kaynes", "sector": "FMCG"},
    {"symbol": "KFINTECH", "name": "KFintech", "sector": "Financial Services"},
    {"symbol": "MANKIND", "name": "Mankind", "sector": "Pharmaceuticals"},
    {"symbol": "PIIND", "name": "PIInd", "sector": "Industrials"},
    {"symbol": "POONAWALLA", "name": "Poonawalla", "sector": "Finance"},
    {"symbol": "JIOFIN", "name": "Jiofin", "sector": "Finance"},
    {"symbol": "AARTIIND", "name": "Aartiind", "sector": "Industrials"},
    {"symbol": "BSE", "name": "BSE", "sector": "Financial Services"},
    {"symbol": "DMART", "name": "DMart", "sector": "FMCG"},
    {"symbol": "HUDCO", "name": "Hudco", "sector": "Finance"},
    {"symbol": "AUBANK", "name": "Aubank", "sector": "Bank"},
    {"symbol": "CDSL", "name": "CDSL", "sector": "Financial Services"},
    {"symbol": "DIXON", "name": "Dixon", "sector": "FMCG"},
    {"symbol": "SUNPHARMA", "name": "Sunpharma", "sector": "Pharmaceuticals"},
    {"symbol": "AUROPHARMA", "name": "Auropharma", "sector": "Pharmaceuticals"},
    {"symbol": "ABCAPITAL", "name": "ABCapital", "sector": "Finance"},
    {"symbol": "MPHASIS", "name": "Mphasis", "sector": "I.T"},
    {"symbol": "NMDC", "name": "Nmdc", "sector": "Industrials"},
    {"symbol": "IREDA", "name": "IREDA", "sector": "Finance"},
    {"symbol": "TATATECH", "name": "Tatatech", "sector": "I.T"},
    {"symbol": "SBILIFE", "name": "Sbilife", "sector": "Services"},
    {"symbol": "ICICIGI", "name": "Icicigi", "sector": "Services"},
    {"symbol": "IEX", "name": "Iex", "sector": "Financial Services"},
    {"symbol": "TIINDIA", "name": "Tiindia", "sector": "Metals"},
    {"symbol": "HDFCLIFE", "name": "Hdfclife", "sector": "Services"},
    {"symbol": "AMBER", "name": "Amber", "sector": "FMCG"},
    {"symbol": "BDL", "name": "BDL", "sector": "Aerospace & Defence"},
    {"symbol": "BANDHANBNK", "name": "Bandhanbnk", "sector": "Bank"},
    {"symbol": "HAL", "name": "HAL", "sector": "Aerospace & Defence"},
    {"symbol": "ADANIGREEN", "name": "Adanigreen", "sector": "Miscellaneous"},
    {"symbol": "HDFCAMC", "name": "Hdfcamc", "sector": "Finance"},
    {"symbol": "ATGL", "name": "Atgl", "sector": "Industrials"},
    {"symbol": "IOC", "name": "Ioc", "sector": "Industrials"},
    {"symbol": "MANAPPURAM", "name": "Manappuram", "sector": "Finance"},
    {"symbol": "CONCOR", "name": "Concor", "sector": "Services"},
    {"symbol": "RVNL", "name": "RVNL", "sector": "Realty"},
    {"symbol": "POLYCAB", "name": "Polycab", "sector": "Industrials"},
    {"symbol": "KPITTECH", "name": "KPITtech", "sector": "I.T"},
    {"symbol": "MARICO", "name": "Marico", "sector": "FMCG"},
    {"symbol": "360ONE", "name": "360ONE", "sector": "Finance"},
    {"symbol": "IRCTC", "name": "IRCTC", "sector": "Miscellaneous"},
    {"symbol": "SBICARD", "name": "SBIcard", "sector": "Finance"},
    {"symbol": "MAXHEALTH", "name": "Maxhealth", "sector": "Pharmaceuticals"},
    {"symbol": "BANKBARODA", "name": "Bankbaroda", "sector": "Bank"},
    {"symbol": "BANKINDIA", "name": "Bankindia", "sector": "Bank"},
    {"symbol": "CAMS", "name": "CAMS", "sector": "Financial Services"},
    {"symbol": "GAIL", "name": "Gail", "sector": "Industrials"},
    {"symbol": "ANGELONE", "name": "AngelOne", "sector": "Services"},
    {"symbol": "ICICIBANK", "name": "Icicibank", "sector": "Bank"},
    {"symbol": "CYIENT", "name": "Cyient", "sector": "I.T"},
    {"symbol": "MAZDOCK", "name": "Mazdock", "sector": "Aerospace & Defence"},
    {"symbol": "INDUSINDBK", "name": "Indusindbk", "sector": "Bank"},
    {"symbol": "AXISBANK", "name": "Axisbank", "sector": "Bank"},
    {"symbol": "NATIONALUM", "name": "Nationalum", "sector": "Metals"},
    {"symbol": "HCLTECH", "name": "Hcltech", "sector": "I.T"},
    {"symbol": "JINDALSTEL", "name": "Jindalstel", "sector": "Metals"},
    {"symbol": "GLENMARK", "name": "Glenmark", "sector": "Pharmaceuticals"},
    {"symbol": "ZYDUSLIFE", "name": "Zyduslife", "sector": "Pharmaceuticals"},
    {"symbol": "TVSMOTOR", "name": "Tvsmotor", "sector": "Auto"},
    {"symbol": "BSOFT", "name": "Bsoft", "sector": "I.T"},
    {"symbol": "GODREJCP", "name": "Godrejcp", "sector": "FMCG"},
    {"symbol": "UNITDSPR", "name": "Unitdspr", "sector": "FMCG"},
    {"symbol": "BHARTIARTL", "name": "Bhartiartl", "sector": "Telecom"},
    {"symbol": "PNB", "name": "Pnb", "sector": "Bank"},
    {"symbol": "OFSS", "name": "OFSS", "sector": "I.T"},
    {"symbol": "UNIONBANK", "name": "Unionbank", "sector": "Bank"},
    {"symbol": "GRANULES", "name": "Granules", "sector": "Pharmaceuticals"},
    {"symbol": "CANBK", "name": "Canbk", "sector": "Bank"},
    {"symbol": "DIVISLAB", "name": "Divislab", "sector": "Pharmaceuticals"},
    {"symbol": "MARUTI", "name": "Maruti", "sector": "Auto"},
    {"symbol": "JSL", "name": "Jsl", "sector": "Metals"},
    {"symbol": "IGL", "name": "Igl", "sector": "Industrials"},
    {"symbol": "PETRONET", "name": "Petronet", "sector": "Industrials"},
    {"symbol": "BIOCON", "name": "Biocon", "sector": "Pharmaceuticals"},
    {"symbol": "ULTRACEMCO", "name": "Ultracemco", "sector": "Industrials"},
    {"symbol": "UNOMINDA", "name": "Unominda", "sector": "Auto"},
    {"symbol": "TCS", "name": "Tcs", "sector": "I.T"},
    {"symbol": "COFORGE", "name": "Coforge", "sector": "I.T"},
    {"symbol": "NTPC", "name": "Ntpc", "sector": "Miscellaneous"},
    {"symbol": "IIFL", "name": "IIFL", "sector": "Finance"},
    {"symbol": "YESBANK", "name": "Yesbank", "sector": "Bank"},
    {"symbol": "M&MFIN", "name": "M&Mfin", "sector": "Finance"},
    {"symbol": "SOLARINDS", "name": "Solarinds", "sector": "Aerospace & Defence"},
    {"symbol": "GMRAIRPORT", "name": "GMRairport", "sector": "Miscellaneous"},
    {"symbol": "TECHM", "name": "Techm", "sector": "I.T"},
    {"symbol": "NAUKRI", "name": "Naukri", "sector": "I.T"},
    {"symbol": "TORNTPOWER", "name": "Torntpower", "sector": "Miscellaneous"},
    {"symbol": "PFC", "name": "Pfc", "sector": "Finance"},
    {"symbol": "INDIANB", "name": "Indianb", "sector": "Bank"},
    {"symbol": "IDEA", "name": "Idea", "sector": "Telecom"},
    {"symbol": "PAGEIND", "name": "Pageind", "sector": "FMCG"},
    {"symbol": "ASTRAL", "name": "Astral", "sector": "FMCG"},
    {"symbol": "FORTIS", "name": "Fortis", "sector": "Pharmaceuticals"},
    {"symbol": "DLF", "name": "Dlf", "sector": "Realty"},
    {"symbol": "POWERGRID", "name": "Powergrid", "sector": "Miscellaneous"},
    {"symbol": "ADANIPORTS", "name": "Adaniports", "sector": "Industrials"},
    {"symbol": "IRB", "name": "IRB", "sector": "Realty"},
    {"symbol": "RECLTD", "name": "Recltd", "sector": "Finance"},
    {"symbol": "TITAGARH", "name": "Titagarh", "sector": "FMCG"},
    {"symbol": "BAJAJ-AUTO", "name": "Bajaj-Auto", "sector": "Auto"},
    {"symbol": "BAJAJFINSV", "name": "Bajajfinsv", "sector": "Finance"},
    {"symbol": "NHPC", "name": "NHPC", "sector": "Miscellaneous"},
    {"symbol": "OIL", "name": "Oil", "sector": "Oils"},
    {"symbol": "JSWENERGY", "name": "JSWenergy", "sector": "Miscellaneous"},
    {"symbol": "GODREJPROP", "name": "Godrejprop", "sector": "Realty"},
    {"symbol": "JUBLFOOD", "name": "Jublfood", "sector": "Quick Service Restaurant"},
    {"symbol": "PERSISTENT", "name": "Persistent", "sector": "I.T"},
    {"symbol": "SJVN", "name": "SJVN", "sector": "Miscellaneous"},
    {"symbol": "OBEROIRLTY", "name": "Oberoirlty", "sector": "Realty"},
    {"symbol": "PRESTIGE", "name": "Prestige", "sector": "Realty"},
    {"symbol": "COALINDIA", "name": "Coalindia", "sector": "Industrials"},
    {"symbol": "DALBHARAT", "name": "Dalbharat", "sector": "Industrials"},
    {"symbol": "MUTHOOTFIN", "name": "Muthootfin", "sector": "Finance"},
    {"symbol": "LTF", "name": "LTF", "sector": "Finance"},
    {"symbol": "PGEL", "name": "PGEL", "sector": "FMCG"},
    {"symbol": "APLAPOLLO", "name": "Aplapollo", "sector": "Metals"},
    {"symbol": "MCX", "name": "MCX", "sector": "Financial Services"},
    {"symbol": "NBCC", "name": "NBCC", "sector": "Realty"},
    {"symbol": "IRFC", "name": "IRFC", "sector": "Finance"},
    {"symbol": "INDUSTOWER", "name": "Industower", "sector": "Telecom"},
    {"symbol": "KALYANKJIL", "name": "Kalyankjil", "sector": "Miscellaneous"},
    {"symbol": "ABFRL", "name": "ABFRL", "sector": "FMCG"},
    {"symbol": "LODHA", "name": "Lodha", "sector": "Realty"},
    {"symbol": "SONACOMS", "name": "Sonacoms", "sector": "Auto"},
    {"symbol": "ETERNAL", "name": "Eternal", "sector": "I.T"},
    {"symbol": "NYKAA", "name": "Nykaa", "sector": "I.T"},
    {"symbol": "POLICYBZR", "name": "Policybzr", "sector": "I.T"},
    {"symbol": "PAYTM", "name": "Paytm", "sector": "I.T"},
    {"symbol": "INOXWIND", "name": "Inoxwind", "sector": "FMCG"},
    {"symbol": "ADANIENSOL", "name": "Adaniensol", "sector": "Miscellaneous"},
    {"symbol": "SYNGENE", "name": "Syngene", "sector": "Pharmaceuticals"},
    {"symbol": "IDFCFIRSTB", "name": "Idfcfirstb", "sector": "Bank"},
    {"symbol": "INDIGO", "name": "Indigo", "sector": "Services"},
    {"symbol": "ALKEM", "name": "Alkem", "sector": "Pharmaceuticals"},
    {"symbol": "CROMPTON", "name": "Crompton", "sector": "FMCG"},
    {"symbol": "MGL", "name": "Mgl", "sector": "Industrials"},
    {"symbol": "LTIM", "name": "Ltim", "sector": "I.T"},
    {"symbol": "RBLBANK", "name": "Rblbank", "sector": "Bank"},
    {"symbol": "ICICIPRULI", "name": "Icicipruli", "sector": "Services"},
    {"symbol": "PNBHOUSING", "name": "PNBhousing", "sector": "Finance"},
    {"symbol": "VBL", "name": "Vbl", "sector": "FMCG"}
]

# Model parameters
LSTM_LOOKBACK_DAYS = 7
TRAIN_TEST_SPLIT = 0.8
EPOCHS = 10
BATCH_SIZE = 32