# app/config.py
import os
from pathlib import Path

# Project directories
BASE_DIR = Path(__file__).parent.parent.absolute()
OUTPUT_DIR = os.path.join(BASE_DIR, "output")
DATA_DIR = os.path.join(OUTPUT_DIR, "data")
PLOTS_DIR = os.path.join(OUTPUT_DIR, "plots")

# Create directories if they don't exist
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(PLOTS_DIR, exist_ok=True)

# Sector mapping for stocks
SECTOR_MAPPING = {
    # NIFTY METAL
    "NATIONALUM.NS": "NIFTY_METAL",
    "SAIL.NS": "NIFTY_METAL",
    "HINDALCO.NS": "NIFTY_METAL",
    "TATASTEEL.NS": "NIFTY_METAL",
    "JSL.NS": "NIFTY_METAL",
    "VEDL.NS": "NIFTY_METAL",
    "NMDC.NS": "NIFTY_METAL",
    "APLAPOLLO.NS": "NIFTY_METAL",
    "COALINDIA.NS": "NIFTY_METAL",
    "JINDALSTEL.NS": "NIFTY_METAL",
    "JSWSTEEL.NS": "NIFTY_METAL",
    "HINDCOPPER.NS": "NIFTY_METAL",
    "ADANIENT.NS": "NIFTY_METAL",
    "HINDZINC.NS": "NIFTY_METAL",
    "MOIL.NS": "NIFTY_METAL",
    "RATNAMANI.NS": "NIFTY_METAL",
    "WELCORP.NS": "NIFTY_METAL",
    
    # NIFTY CONSUMER DURABLES
    "DIXON.NS": "NIFTY_CONSR_DURBL",
    "ORIENTELEC.NS": "NIFTY_CONSR_DURBL",
    "AMBER.NS": "NIFTY_CONSR_DURBL",
    "HAVELLS.NS": "NIFTY_CONSR_DURBL",
    "TTKPRESTIG.NS": "NIFTY_CONSR_DURBL",
    "WHIRLPOOL.NS": "NIFTY_CONSR_DURBL",
    "RELAXO.NS": "NIFTY_CONSR_DURBL",
    "RAJESHEXPO.NS": "NIFTY_CONSR_DURBL",
    "KAJARIACER.NS": "NIFTY_CONSR_DURBL",
    "TITAN.NS": "NIFTY_CONSR_DURBL",
    "CROMPTON.NS": "NIFTY_CONSR_DURBL",
    "BLUESTARCO.NS": "NIFTY_CONSR_DURBL",
    "VGUARD.NS": "NIFTY_CONSR_DURBL",
    "BATAINDIA.NS": "NIFTY_CONSR_DURBL",
    "VOLTAS.NS": "NIFTY_CONSR_DURBL",
    
    # NIFTY ENERGY
    "ADANIGREEN.NS": "NIFTY_ENERGY",
    "ONGC.NS": "NIFTY_ENERGY",
    "POWERGRID.NS": "NIFTY_ENERGY",
    "NTPC.NS": "NIFTY_ENERGY",
    "RELIANCE.NS": "NIFTY_ENERGY",
    "BPCL.NS": "NIFTY_ENERGY",
    "TATAPOWER.NS": "NIFTY_ENERGY",
    "GAIL.NS": "NIFTY_ENERGY",
    "ADANIENSOL.NS": "NIFTY_ENERGY",
    "IOC.NS": "NIFTY_ENERGY",
    
    # NIFTY PHARMA
    "LAURUSLABS.NS": "NIFTY_PHARMA",
    "STAR.NS": "NIFTY_PHARMA",
    "GRANULES.NS": "NIFTY_PHARMA",
    "NATCOPHARM.NS": "NIFTY_PHARMA",
    "DIVISLAB.NS": "NIFTY_PHARMA",
    "BIOCON.NS": "NIFTY_PHARMA",
    "CIPLA.NS": "NIFTY_PHARMA",
    "ZYDUSLIFE.NS": "NIFTY_PHARMA",
    "IPCALAB.NS": "NIFTY_PHARMA",
    "SANOFI.NS": "NIFTY_PHARMA",
    "LUPIN.NS": "NIFTY_PHARMA",
    "AUROPHARMA.NS": "NIFTY_PHARMA",
    "SUNPHARMA.NS": "NIFTY_PHARMA",
    "ABBOTINDIA.NS": "NIFTY_PHARMA",
    "DRREDDY.NS": "NIFTY_PHARMA",
    "PFIZER.NS": "NIFTY_PHARMA",
    "ALKEM.NS": "NIFTY_PHARMA",
    "APLLTD.NS": "NIFTY_PHARMA",
    "GLENMARK.NS": "NIFTY_PHARMA",
    "GLAND.NS": "NIFTY_PHARMA",
    "TORNTPHARM.NS": "NIFTY_PHARMA",
    "SYNGENE.NS": "NIFTY_PHARMA",
    "METROPOLIS.NS": "NIFTY_PHARMA",
    "LALPATHLAB.NS": "NIFTY_PHARMA",
    "MAXHEALTH.NS": "NIFTY_PHARMA",
    "APOLLOHOSP.NS": "NIFTY_PHARMA",
    
    # NIFTY OIL AND GAS
    "GSPL.NS": "NIFTY_OIL_AND_GAS",
    "GUJGASLTD.NS": "NIFTY_OIL_AND_GAS",
    "JIOFIN.NS": "NIFTY_OIL_AND_GAS",
    "ONGC.NS": "NIFTY_OIL_AND_GAS",
    "RELIANCE.NS": "NIFTY_OIL_AND_GAS",
    "OIL.NS": "NIFTY_OIL_AND_GAS",
    "MGL.NS": "NIFTY_OIL_AND_GAS",
    "ATGL.NS": "NIFTY_OIL_AND_GAS",
    "BPCL.NS": "NIFTY_OIL_AND_GAS",
    "GAIL.NS": "NIFTY_OIL_AND_GAS",
    "CASTROLIND.NS": "NIFTY_OIL_AND_GAS",
    "HINDPETRO.NS": "NIFTY_OIL_AND_GAS",
    "IOC.NS": "NIFTY_OIL_AND_GAS",
    "IGL.NS": "NIFTY_OIL_AND_GAS",
    "PETRONET.NS": "NIFTY_OIL_AND_GAS",
    "AEGISLOG.NS": "NIFTY_OIL_AND_GAS",
    
    # NIFTY AUTO
    "SONACOMS.NS": "NIFTY_AUTO",
    "MOTHERSON.NS": "NIFTY_AUTO",
    "MRF.NS": "NIFTY_AUTO",
    "BHARATFORG.NS": "NIFTY_AUTO",
    "BAJAJ-AUTO.NS": "NIFTY_AUTO",
    "BAJAJAUTO.NS": "NIFTY_AUTO",
    "BALKRISIND.NS": "NIFTY_AUTO",
    "M&M.NS": "NIFTY_AUTO",
    "TATAMOTORS.NS": "NIFTY_AUTO",
    "ASHOKLEY.NS": "NIFTY_AUTO",
    "EICHERMOT.NS": "NIFTY_AUTO",
    "TVSMOTOR.NS": "NIFTY_AUTO",
    "HEROMOTOCO.NS": "NIFTY_AUTO",
    "EXIDEIND.NS": "NIFTY_AUTO",
    "MARUTI.NS": "NIFTY_AUTO",
    "ARE&M.NS": "NIFTY_AUTO",
    "BOSCHLTD.NS": "NIFTY_AUTO",
    "TIINDIA.NS": "NIFTY_AUTO",
    
    # NIFTY FINANCIAL SERVICES
    "HDFCAMC.NS": "NIFTY_FIN_SERVICE",
    "RECLTD.NS": "NIFTY_FIN_SERVICE",
    "CHOLAFIN.NS": "NIFTY_FIN_SERVICE",
    "KOTAKBANK.NS": "NIFTY_FIN_SERVICE",
    "SBILIFE.NS": "NIFTY_FIN_SERVICE",
    "BAJAJFINSV.NS": "NIFTY_FIN_SERVICE",
    "HDFCBANK.NS": "NIFTY_FIN_SERVICE",
    "M&MFIN.NS": "NIFTY_FIN_SERVICE",
    "BAJFINANCE.NS": "NIFTY_FIN_SERVICE",
    "PEL.NS": "NIFTY_FIN_SERVICE",
    "PFC.NS": "NIFTY_FIN_SERVICE",
    "SBIN.NS": "NIFTY_FIN_SERVICE",
    "IEX.NS": "NIFTY_FIN_SERVICE",
    "ICICIBANK.NS": "NIFTY_FIN_SERVICE",
    "AXISBANK.NS": "NIFTY_FIN_SERVICE",
    "HDFCLIFE.NS": "NIFTY_FIN_SERVICE",
    "ICICIPRULI.NS": "NIFTY_FIN_SERVICE",
    "ICICIGI.NS": "NIFTY_FIN_SERVICE",
    "MUTHOOTFIN.NS": "NIFTY_FIN_SERVICE",

    # NIFTY FINSERV25-50
    "SHRIRAMFIN.NS": "NIFTY_FINSERV25_50",
    "SBICARD.NS": "NIFTY_FINSERV25_50",
    "LICHSGFIN.NS": "NIFTY_FINSERV25_50",
    
    # NIFTY MEDIA
    "PVRINOX.NS": "NIFTY_MEDIA",
    "DISHTV.NS": "NIFTY_MEDIA",
    "SAREGAMA.NS": "NIFTY_MEDIA",
    "SUNTV.NS": "NIFTY_MEDIA",
    "NETWORK18.NS": "NIFTY_MEDIA",
    "HATHWAY.NS": "NIFTY_MEDIA",
    "ZEEL.NS": "NIFTY_MEDIA",
    "NAZARA.NS": "NIFTY_MEDIA",
    
    # NIFTY PRIVATE BANKS
    "CUB.NS": "NIFTY_PVT_BANK",
    "RBLBANK.NS": "NIFTY_PVT_BANK",
    "KOTAKBANK.NS": "NIFTY_PVT_BANK",
    "HDFCBANK.NS": "NIFTY_PVT_BANK",
    "BANDHANBNK.NS": "NIFTY_PVT_BANK",
    "INDUSINDBK.NS": "NIFTY_PVT_BANK",
    "IDFCFIRSTB.NS": "NIFTY_PVT_BANK",
    "ICICIBANK.NS": "NIFTY_PVT_BANK",
    "AXISBANK.NS": "NIFTY_PVT_BANK",
    "FEDERALBNK.NS": "NIFTY_PVT_BANK",
    
    # NIFTY HEALTHCARE
    "LALPATHLAB.NS": "NIFTY_HEALTHCARE",
    "SYNGENE.NS": "NIFTY_HEALTHCARE",
    "METROPOLIS.NS": "NIFTY_HEALTHCARE",
    "APOLLOHOSP.NS": "NIFTY_HEALTHCARE",
    "MAXHEALTH.NS": "NIFTY_HEALTHCARE",
    
    # NIFTY BANK
    "KOTAKBANK.NS": "NIFTY_BANK",
    "CANBK.NS": "NIFTY_BANK",
    "HDFCBANK.NS": "NIFTY_BANK",
    "INDUSINDBK.NS": "NIFTY_BANK",
    "SBIN.NS": "NIFTY_BANK",
    "IDFCFIRSTB.NS": "NIFTY_BANK",
    "BANKBARODA.NS": "NIFTY_BANK",
    "ICICIBANK.NS": "NIFTY_BANK",
    "AXISBANK.NS": "NIFTY_BANK",
    "AUBANK.NS": "NIFTY_BANK",
    "PNB.NS": "NIFTY_BANK",
    "FEDERALBNK.NS": "NIFTY_BANK",
    
    # NIFTY CONSUMPTION
    "DIXON.NS": "NIFTY_CONSUMPTION",
    "ORIENTELEC.NS": "NIFTY_CONSUMPTION",
    "AMBER.NS": "NIFTY_CONSUMPTION",
    "HAVELLS.NS": "NIFTY_CONSUMPTION",
    "TTKPRESTIG.NS": "NIFTY_CONSUMPTION",
    "WHIRLPOOL.NS": "NIFTY_CONSUMPTION",
    "RELAXO.NS": "NIFTY_CONSUMPTION",
    "RAJESHEXPO.NS": "NIFTY_CONSUMPTION",
    "KAJARIACER.NS": "NIFTY_CONSUMPTION",
    "TITAN.NS": "NIFTY_CONSUMPTION",
    "CROMPTON.NS": "NIFTY_CONSUMPTION",
    "BLUESTARCO.NS": "NIFTY_CONSUMPTION",
    "VGUARD.NS": "NIFTY_CONSUMPTION",
    "BATAINDIA.NS": "NIFTY_CONSUMPTION",
    "VOLTAS.NS": "NIFTY_CONSUMPTION",
    
    # NIFTY PSU BANK
    "CANBK.NS": "NIFTY_PSU_BANK",
    "CENTRALBK.NS": "NIFTY_PSU_BANK",
    "INDIANB.NS": "NIFTY_PSU_BANK",
    "SBIN.NS": "NIFTY_PSU_BANK",
    "BANKINDIA.NS": "NIFTY_PSU_BANK",
    "BANKBARODA.NS": "NIFTY_PSU_BANK",
    "UNIONBANK.NS": "NIFTY_PSU_BANK",
    "UCOBANK.NS": "NIFTY_PSU_BANK",
    "MAHABANK.NS": "NIFTY_PSU_BANK",
    "PNB.NS": "NIFTY_PSU_BANK",
    "J&KBANK.NS": "NIFTY_PSU_BANK",
    "IOB.NS": "NIFTY_PSU_BANK",
    
    # NIFTY REALTY
    "SUNTECK.NS": "NIFTY_REALTY",
    "PRESTIGE.NS": "NIFTY_REALTY",
    "OBEROIRLTY.NS": "NIFTY_REALTY",
    "BRIGADE.NS": "NIFTY_REALTY",
    "DLF.NS": "NIFTY_REALTY",
    "SOBHA.NS": "NIFTY_REALTY",
    "LODHA.NS": "NIFTY_REALTY",
    "EMBDL.NS": "NIFTY_REALTY",
    "PHOENIXLTD.NS": "NIFTY_REALTY",
    "GODREJPROP.NS": "NIFTY_REALTY",
    
    # NIFTY CONSUMER
    "MARICO.NS": "NIFTY_CONSUMER",
    "UNITDSPR.NS": "NIFTY_CONSUMER",
    "RADICO.NS": "NIFTY_CONSUMER",
    "EMAMILTD.NS": "NIFTY_CONSUMER",
    "ITC.NS": "NIFTY_CONSUMER",
    "VBL.NS": "NIFTY_CONSUMER",
    "UBL.NS": "NIFTY_CONSUMER",
    "TATACONSUM.NS": "NIFTY_CONSUMER",
    "NESTLEIND.NS": "NIFTY_CONSUMER",
    "HINDUNILVR.NS": "NIFTY_CONSUMER",
    "BRITANNIA.NS": "NIFTY_CONSUMER",
    "COLPAL.NS": "NIFTY_CONSUMER",
    "PGHH.NS": "NIFTY_CONSUMER",
    "DABUR.NS": "NIFTY_CONSUMER",
    "GODREJCP.NS": "NIFTY_CONSUMER",
    
    # NIFTY IT
    "LTIM.NS": "NIFTY_IT",
    "PERSISTENT.NS": "NIFTY_IT",
    "MPHASIS.NS": "NIFTY_IT",
    "WIPRO.NS": "NIFTY_IT",
    "LTTS.NS": "NIFTY_IT",
    "HCLTECH.NS": "NIFTY_IT",
    "TECHM.NS": "NIFTY_IT",
    "INFY.NS": "NIFTY_IT",
    "COFORGE.NS": "NIFTY_IT",
    "TCS.NS": "NIFTY_IT"
}

# Top Indian stocks to analyze 
TOP_STOCKS = [
    {"symbol": "NATIONALUM.NS", "name": "Nationalum"},
    {"symbol": "SAIL.NS", "name": "Sail"},
    {"symbol": "HINDALCO.NS", "name": "Hindalco"},
    {"symbol": "TATASTEEL.NS", "name": "Tatasteel"},
    {"symbol": "JSL.NS", "name": "Jsl"},
    {"symbol": "VEDL.NS", "name": "Vedl"},
    {"symbol": "NMDC.NS", "name": "Nmdc"},
    {"symbol": "APLAPOLLO.NS", "name": "Aplapollo"},
    {"symbol": "COALINDIA.NS", "name": "Coalindia"},
    {"symbol": "JINDALSTEL.NS", "name": "Jindalstel"},
    {"symbol": "JSWSTEEL.NS", "name": "Jswsteel"},
    {"symbol": "HINDCOPPER.NS", "name": "Hindcopper"},
    {"symbol": "ADANIENT.NS", "name": "Adanient"},
    {"symbol": "BATAINDIA.NS", "name": "Bataindia"},
    {"symbol": "TITAN.NS", "name": "Titan"},
    {"symbol": "HAVELLS.NS", "name": "Havells"},
    {"symbol": "CROMPTON.NS", "name": "Cromptom"},
    {"symbol": "VOLTAS.NS", "name": "Voltas"},
    {"symbol": "DIXON.NS", "name": "Dixon"},
    {"symbol": "TIINDIA.NS", "name": "Tiindia"},
    {"symbol": "MOTHERSON.NS", "name": "Motherson"},
    {"symbol": "TVSMOTOR.NS", "name": "Tvsmotor"},
    {"symbol": "TATAMOTORS.NS", "name": "Tatamotors"},
    {"symbol": "HEROMOTOCO.NS", "name": "Heromotoco"},
    {"symbol": "EXIDEIND.NS", "name": "Exideind"},
    {"symbol": "MARUTI.NS", "name": "Maruti"},
    {"symbol": "BHARATFORG.NS", "name": "Bharatforg"},
    {"symbol": "BOSCHLTD.NS", "name": "Boschltd"},
    {"symbol": "BAJAJAUTO.NS", "name": "Bajajauto"},
    {"symbol": "MRF.NS", "name": "Mrf"},
    {"symbol": "ASHOKLEY.NS", "name": "Ashokley"},
    {"symbol": "EICHERMOT.NS", "name": "Eichermot"},
    {"symbol": "BALKRISIND.NS", "name": "Balkrisind"},
    {"symbol": "SONACOMS.NS", "name": "Sonacoms"},
    {"symbol": "M&M.NS", "name": "M&m"},
    {"symbol": "ABBOTINDIA.NS", "name": "Abbotindia"},
    {"symbol": "DIVISLAB.NS", "name": "Divislab"},
    {"symbol": "APOLLOHOSP.NS", "name": "Apollohosp"},
    {"symbol": "ALKEM.NS", "name": "Alkem"},
    {"symbol": "LALPATHLAB.NS", "name": "Lalpathlab"},
    {"symbol": "IPCALAB.NS", "name": "Ipcalab"},
    {"symbol": "GLENMARK.NS", "name": "Glenmark"},
    {"symbol": "DRREDDY.NS", "name": "Drreddy"},
    {"symbol": "AUROPHARMA.NS", "name": "Auropharma"},
    {"symbol": "LUPIN.NS", "name": "Lupin"},
    {"symbol": "SUNPHARMA.NS", "name": "Sunpharma"},
    {"symbol": "MAXHEALTH.NS", "name": "Maxhealth"},
    {"symbol": "LAURUSLABS.NS", "name": "Lauraslabs"},
    {"symbol": "ZYDUSLIFE.NS", "name": "Zyduslife"},
    {"symbol": "TORNTPHARM.NS", "name": "Torntpharm"},
    {"symbol": "GRANULES.NS", "name": "Granules"},
    {"symbol": "BIOCON.NS", "name": "Biocon"},
    {"symbol": "CIPLA.NS", "name": "Cipla"},
    {"symbol": "METROPOLIS.NS", "name": "Metropolis"},
    {"symbol": "SYNGENE.NS", "name": "Syngene"},
    {"symbol": "COLPAL.NS", "name": "Colpal"},
    {"symbol": "GODREJCP.NS", "name": "Godrejcp"},
    {"symbol": "UBL.NS", "name": "Ubl"},
    {"symbol": "UNITDSPR.NS", "name": "Unitdspr"},
    {"symbol": "DABUR.NS", "name": "Dabur"},
    {"symbol": "MARICO.NS", "name": "Marico"},
    {"symbol": "VBL.NS", "name": "Vbl"},
    {"symbol": "ITC.NS", "name": "Itc"},
    {"symbol": "NESTLEIND.NS", "name": "Nestleind"},
    {"symbol": "TATACONSUM.NS", "name": "Tataconsum"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindunilvr"},
    {"symbol": "BRITANNIA.NS", "name": "Britannia"},
    {"symbol": "RELIANCE.NS", "name": "Reliance"},
    {"symbol": "ADANIGREEN.NS", "name": "Adanigreen"},
    {"symbol": "TATAPOWER.NS", "name": "Tatapower"},
    {"symbol": "BPCL.NS", "name": "Bpcl"},
    {"symbol": "NTPC.NS", "name": "Ntpc"},
    {"symbol": "ONGC.NS", "name": "Ongc"},
    {"symbol": "POWERGRID.NS", "name": "Powergrid"},
    {"symbol": "ADANIENSOL.NS", "name": "Adaniensol"},
    {"symbol": "IOC.NS", "name": "Ioc"},
    {"symbol": "GAIL.NS", "name": "Gail"},
    {"symbol": "HINDPETRO.NS", "name": "Hindpetro"},
    {"symbol": "JIOFIN.NS", "name": "Jiofin"},
    {"symbol": "OIL.NS", "name": "Oil"},
    {"symbol": "IGL.NS", "name": "Igl"},
    {"symbol": "ATGL.NS", "name": "Atgl"},
    {"symbol": "GUJGASLTD.NS", "name": "Gujgasltd"},
    {"symbol": "PETRONET.NS", "name": "Petronet"},
    {"symbol": "MGL.NS", "name": "Mgl"},
    {"symbol": "LTTS.NS", "name": "Ltts"},
    {"symbol": "COFORGE.NS", "name": "Coforge"},
    {"symbol": "TCS.NS", "name": "Tcs"},
    {"symbol": "PERSISTENT.NS", "name": "Persistent"},
    {"symbol": "MPHASIS.NS", "name": "Mphasis"},
    {"symbol": "LTIM.NS", "name": "Ltim"},
    {"symbol": "BSOFT.NS", "name": "Bsoft"},
    {"symbol": "WIPRO.NS", "name": "Wipro"},
    {"symbol": "HCLTECH.NS", "name": "Hcltech"},
    {"symbol": "TECHM.NS", "name": "Techm"},
    {"symbol": "INFY.NS", "name": "Infy"},
    {"symbol": "SUNTV.NS", "name": "Suntv"},
    {"symbol": "PVRINOX.NS", "name": "Pvrinox"},
    {"symbol": "NAZARA.NS", "name": "Nazara"},
    {"symbol": "NETWORK18.NS", "name": "Network18"},
    {"symbol": "SAREGAMA.NS", "name": "Saregama"},
    {"symbol": "ZEEL.NS", "name": "Zeel"},
    {"symbol": "DISHTV.NS", "name": "Dishtv"},
    {"symbol": "HATHWAY.NS", "name": "Hathway"},
    {"symbol": "SBIN.NS", "name": "Sbin"},
    {"symbol": "CANBK.NS", "name": "Canbk"},
    {"symbol": "BANKINDIA.NS", "name": "Bankindia"},
    {"symbol": "PNB.NS", "name": "Pnb"},
    {"symbol": "UNIONBANK.NS", "name": "Unionbank"},
    {"symbol": "BANKBARODA.NS", "name": "Bankbaroda"},
    {"symbol": "INDIANB.NS", "name": "Indianb"},
    {"symbol": "HDFCBANK.NS", "name": "Hdfcbank"},
    {"symbol": "KOTAKBANK.NS", "name": "Kotakbank"},
    {"symbol": "CUB.NS", "name": "Cub"},
    {"symbol": "BANDHANBNK.NS", "name": "Bandhanbnk"},
    {"symbol": "IDFCFIRSTB.NS", "name": "Idfcfirstb"},
    {"symbol": "FEDERALBNK.NS", "name": "Federalbnk"},
    {"symbol": "RBLBANK.NS", "name": "Rblbank"},
    {"symbol": "AXISBANK.NS", "name": "Axisbank"},
    {"symbol": "ICICIBANK.NS", "name": "Icicibank"},
    {"symbol": "INDUSINDBK.NS", "name": "Indusindbk"},
    {"symbol": "ICICIGI.NS", "name": "Icicigi"},
    {"symbol": "SBILIFE.NS", "name": "Sbilife"},
    {"symbol": "IEX.NS", "name": "Iex"},
    {"symbol": "PEL.NS", "name": "Pel"},
    {"symbol": "HDFCLIFE.NS", "name": "Hdfclife"},
    {"symbol": "PFC.NS", "name": "Pfc"},
    {"symbol": "M&MFIN.NS", "name": "M&mfin"},
    {"symbol": "RECLTD.NS", "name": "Recltd"},
    {"symbol": "ICICIPRULI.NS", "name": "Icicipruli"},
    {"symbol": "BAJAJFINSV.NS", "name": "Bajajfinsv"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajfinance"},
    {"symbol": "MUTHOOTFIN.NS", "name": "Muthootfin"},
    {"symbol": "HDFCAMC.NS", "name": "Hdfcamc"},
    {"symbol": "CHOLAFIN.NS", "name": "Cholafin"},
    {"symbol": "LODHA.NS", "name": "Lodha"},
    {"symbol": "GODREJPROP.NS", "name": "Godrejprop"},
    {"symbol": "PRESTIGE.NS", "name": "Prestige"},
    {"symbol": "OBEROIRLTY.NS", "name": "Oberoirlty"},
    {"symbol": "DLF.NS", "name": "Dlf"},
    {"symbol": "HUDCO.NS", "name": "Hudco"}
]

# Model parameters
LSTM_LOOKBACK_DAYS = 7
TRAIN_TEST_SPLIT = 0.8
EPOCHS = 10
BATCH_SIZE = 32